This notebook is designed to be run in sequential order. The wandb report can be found below.
https://api.wandb.ai/links/pkotchav-carnegie-mellon-university/m1xnkkuk

The final model used was the ASR Network as is in this current version of the notebook.

# Installs

In [ ]:
%pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchtext==0.14.1 torchaudio==0.13.1 torchdata==0.5.1 --extra-index-url https://download.pytorch.org/whl/cu117 -q

WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)


This may take a while

In [ ]:
!pip install wandb --quiet
!pip install python-Levenshtein -q
!pip install torchsummaryX==1.3.0
!pip install pandas==1.5.2
# !git clone --recursive https://github.com/parlance/ctcdecode.git
# !pip install wget -q
# %cd ctcdecode
# !pip install . -q
# %cd ..

WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
Requirement already satisfied: torchsummaryX==1.3.0 in /usr/local/lib/python3.10/dist-packages (1.3.0)
Requirement already satisfied: torch in /usr/local/lib/python3.10/dist-packages (from torchsummaryX==1.3.0) (1.13.1+cu117)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from torchsummaryX==1.3.0) (1.26.4)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from torchsummaryX==1.3.0) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->torchsummaryX==1.3.0) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->torchsummaryX==1.3.0) (2024.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch->torchsummaryX==1.3.0) (4.12.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->torchsummaryX==1.3.0) (1.16.0)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)
Requirement already satisfied: pandas==1.5.2 in /usr/local/lib/python3.10/dist-packages (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas==1.5.2) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas==1.5.2) (2024.2)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas==1.5.2) (1.26.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas==1.5.2) (1.16.0)
WARNING: Ignoring invalid distribution -andas (/usr/local/lib/python3.10/dist-packages)

# Imports

In [ ]:
import torch
import random
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
from torchsummaryX import summary
from torch.utils.data import Dataset, DataLoader
from torch.nn.utils.rnn import pad_sequence, pack_padded_sequence, pad_packed_sequence

import torchaudio.transforms as tat

from sklearn.metrics import accuracy_score
import gc

import zipfile
import pandas as pd
from tqdm import tqdm
import os
import datetime

# imports for decoding and distance calculation
import ctcdecode
import Levenshtein
from ctcdecode import CTCBeamDecoder

import warnings
warnings.filterwarnings('ignore')

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Device: ", device)

Device:  cuda

In [ ]:
print(pd.__version__)

1.5.2

In [ ]:
pip show torchsummaryX

Name: torchsummaryX
Version: 1.3.0
Summary: Improved visualization tool of torchsummary.
Home-page: https://github.com/nmhkahn/torchsummaryX
Author: Namhyuk Ahn
Author-email: nmhkahn@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.10/dist-packages
Requires: numpy, pandas, torch
Required-by:

# Kaggle Setup

In [ ]:
!pip install --upgrade --force-reinstall --no-deps kaggle==1.5.8 -q
!mkdir /root/.kaggle

with open("/root/.kaggle/kaggle.json", "w+") as f:
    f.write('{"username":"paulkotchavong","key":"42477bb8c1877b51a852f26c36c06fd3"}')

!chmod 600 /root/.kaggle/kaggle.json

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 3.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Building wheel for kaggle (setup.py) ... done

In [ ]:
!kaggle competitions download -c hw3p2-785-f24

Downloading hw3p2-785-f24.zip to /content
100% 3.96G/3.97G [00:42<00:00, 142MB/s]
100% 3.97G/3.97G [00:43<00:00, 99.2MB/s]

In [ ]:
'''
This will take a couple minutes, but you should see at least the following:
11-785-f24-hw3p2  ctcdecode  hw3p2asr-f24.zip  sample_data
'''
!unzip -q hw3p2-785-f24.zip
!ls

11785-f24-hw3p2  ctcdecode  hw3p2-785-f24.zip  sample_data

# Google Drive

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

# Dataset and Dataloader

In [ ]:
# ARPABET PHONEME MAPPING
# DO NOT CHANGE

CMUdict_ARPAbet = {
    "" : " ",
    "[SIL]": "-", "NG": "G", "F" : "f", "M" : "m", "AE": "@",
    "R"    : "r", "UW": "u", "N" : "n", "IY": "i", "AW": "W",
    "V"    : "v", "UH": "U", "OW": "o", "AA": "a", "ER": "R",
    "HH"   : "h", "Z" : "z", "K" : "k", "CH": "C", "W" : "w",
    "EY"   : "e", "ZH": "Z", "T" : "t", "EH": "E", "Y" : "y",
    "AH"   : "A", "B" : "b", "P" : "p", "TH": "T", "DH": "D",
    "AO"   : "c", "G" : "g", "L" : "l", "JH": "j", "OY": "O",
    "SH"   : "S", "D" : "d", "AY": "Y", "S" : "s", "IH": "I",
    "[SOS]": "[SOS]", "[EOS]": "[EOS]"
}

CMUdict = list(CMUdict_ARPAbet.keys())
ARPAbet = list(CMUdict_ARPAbet.values())


PHONEMES = CMUdict[:-2]
LABELS = ARPAbet[:-2]

In [ ]:
# put the phonemes into alphabetical order
PHONEMES.sort()
LABELS = [CMUdict_ARPAbet[i] for i in PHONEMES]

In [ ]:
# You might want to play around with the mapping as a sanity check here
print(PHONEMES)
print(LABELS)
print(len(PHONEMES))
print(len(LABELS))

['', '[SIL]', 'NG', 'F', 'M', 'AE', 'R', 'UW', 'N', 'IY', 'AW', 'V', 'UH', 'OW', 'AA', 'ER', 'HH', 'Z', 'K', 'CH', 'W', 'EY', 'ZH', 'T', 'EH', 'Y', 'AH', 'B', 'P', 'TH', 'DH', 'AO', 'G', 'L', 'JH', 'OY', 'SH', 'D', 'AY', 'S', 'IH']
['_', '-', 'G', 'f', 'm', '@', 'r', 'u', 'n', 'i', 'W', 'v', 'U', 'o', 'a', 'R', 'h', 'z', 'k', 'C', 'w', 'e', 'Z', 't', 'E', 'y', 'A', 'b', 'p', 'T', 'D', 'c', 'g', 'l', 'j', 'O', 'S', 'd', 'Y', 's', 'I']
41
41

In [ ]:
mfcc_dir = os.path.join('/content/11785-f24-hw3p2', "train-clean-100", 'mfcc')
transcript_dir = os.path.join('/content/11785-f24-hw3p2', "train-clean-100", 'transcript')

# might as well load it in order
# mfcc_name = os.listdir(self.mfcc_dir)
# mfcc_name.sort()
# transcript_name = os.listdir(self.transcript_dir)
# transcript_name.sort()
mfcc_files = sorted(os.listdir(mfcc_dir))
transcript_files = sorted(os.listdir(transcript_dir))
print(len(mfcc_files))
print(len(transcript_files))

features = []
labels = []

for i in range(len(mfcc_files)):
    mfcc = np.load(os.path.join(mfcc_dir, mfcc_files[i]))
    transcript = np.load(os.path.join(transcript_dir, transcript_files[i]))

    mfcc = (mfcc - np.mean(mfcc, axis=0, keepdims=True))/(np.std(mfcc, axis=0, keepdims=True) + 1e-5)
    transcript = transcript[1:-1]

    features.append(mfcc)
    labels.append(transcript)

28539
28539

KeyboardInterrupt:

In [ ]:
for i in range(3):
    print(features[i].shape)
    print(labels[i].shape)
    print(features[i])
    print(labels[i])

(1404, 28)
(145,)
[[-0.18250355  0.4172915   0.3693044  ... -0.01691582  0.72973764
  -1.5239604 ]
 [-0.13833714  0.48505074  0.4269905  ... -0.06249875 -0.6334915
  -1.4798307 ]
 [-0.17921834  0.6812124   0.49413612 ... -0.29598892  0.80933577
  -1.4886994 ]
 ...
 [-0.7767339  -1.3129497   0.8417389  ... -1.2554015  -2.718656
  -0.13059846]
 [-0.9594661  -1.270711    0.70879424 ... -0.69407827 -1.2275912
  -0.06935827]
 [-1.0557525  -1.2458974   0.6029278  ... -0.7608054  -0.83664864
   0.00604726]]
['[SIL]' 'CH' 'AE' 'P' 'T' 'ER' 'W' 'AH' 'N' '[SIL]' 'M' 'IH' 'S' 'IH' 'Z'
 'R' 'EY' 'CH' 'AH' 'L' 'IH' 'N' 'D' 'IH' 'Z' 'S' 'ER' 'P' 'R' 'AY' 'Z'
 'D' '[SIL]' 'M' 'IH' 'S' 'IH' 'Z' 'R' 'EY' 'CH' 'AH' 'L' 'IH' 'N' 'D'
 '[SIL]' 'L' 'AY' 'V' 'D' '[SIL]' 'JH' 'AH' 'S' 'T' 'W' 'EH' 'R' 'DH' 'AH'
 'AE' 'V' 'AH' 'N' 'L' 'IY' 'AH' 'M' 'EY' 'N' 'R' 'OW' 'D' '[SIL]' 'D'
 'IH' 'P' 'T' '[SIL]' 'D' 'AW' 'N' 'IH' 'N' 'T' 'UW' 'AH' 'L' 'IH' 'T'
 'AH' 'L' 'HH' 'AA' 'L' 'OW' '[SIL]' 'F' 'R' 'IH' 'N' 'JH' 'D' 'W' 'IH'
 'DH' 'AA' 'L' 'D' 'ER' 'Z' 'AH' 'N' 'D' 'L' 'EY' 'D' 'IY' 'Z' 'IH' 'R'
 'D' 'R' 'AA' 'P' 'S' 'AH' 'N' 'D' 'T' 'R' 'AE' 'V' 'ER' 'S' 'T' 'B' 'AY'
 'AH' 'B' 'R' 'UH' 'K' '[SIL]']
(1590, 28)
(194,)
[[-0.9289802  -0.84372056  0.72361    ...  0.00185039 -0.82063234
  -0.2532823 ]
 [-0.9043586  -0.7984215   0.7258564  ... -0.1793299   0.5735964
  -0.33142173]
 [-0.9119843  -0.75323683  0.7060398  ... -0.26046112 -0.92104137
  -0.46128747]
 ...
 [-0.56182927 -1.153044    0.86113495 ...  1.2345575  -0.5314473
  -0.7742266 ]
 [-0.55566806 -0.9758912   1.0223051  ...  1.4328985  -1.2013911
  -0.69446594]
 [-0.65378696 -0.8762093   1.1125716  ...  1.2636961   0.7737454
  -0.6840943 ]]
['[SIL]' 'DH' 'AE' 'T' 'HH' 'AE' 'D' 'IH' 'T' 'S' 'AO' 'R' 'S' 'AH' 'W'
 'EY' 'B' 'AE' 'K' 'IH' 'N' 'DH' 'AH' 'W' 'UH' 'D' 'Z' 'AH' 'V' 'DH' 'AH'
 'OW' 'L' 'D' 'K' 'AH' 'TH' 'B' 'ER' 'T' 'P' 'L' 'EY' 'S' '[SIL]' 'IH' 'T'
 'W' 'AA' 'Z' 'R' 'IH' 'P' 'Y' 'UW' 'T' 'IH' 'D' 'T' 'UW' 'B' 'IY' 'AE'
 'N' 'IH' 'N' 'T' 'R' 'AH' 'K' 'AH' 'T' 'HH' 'EH' 'D' 'L' 'AO' 'NG' 'B'
 'R' 'UH' 'K' 'IH' 'N' 'IH' 'T' 'S' 'ER' 'L' 'IY' 'ER' 'K' 'AO' 'R' 'S'
 'TH' 'R' 'UW' 'DH' 'OW' 'Z' 'W' 'UH' 'D' 'Z' '[SIL]' 'W' 'IH' 'DH' 'D'
 'AA' 'R' 'K' 'S' 'IY' 'K' 'R' 'AH' 'T' 'S' 'AH' 'V' 'P' 'UW' 'L' 'AH' 'N'
 'D' 'K' 'AE' 'S' 'K' 'EY' 'D' '[SIL]' 'B' 'AH' 'T' 'B' 'AY' 'DH' 'AH' 'T'
 'AY' 'M' 'IH' 'T' 'R' 'IY' 'CH' 'T' 'L' 'IH' 'N' 'D' 'Z' 'HH' 'AA' 'L'
 'OW' 'IH' 'T' 'W' 'AA' 'Z' 'AH' 'K' 'W' 'AY' 'AH' 'T' 'W' 'EH' 'L' 'K'
 'AH' 'N' 'D' 'AH' 'K' 'T' 'AH' 'D' 'L' 'IH' 'T' 'AH' 'L' 'S' 'T' 'R' 'IY'
 'M' '[SIL]']
(1390, 28)
(177,)
[[-0.6867226  -0.5823234   1.091869   ... -0.2787405  -0.4849387
  -0.5744934 ]
 [-0.70360845 -0.50163174  1.0381552  ... -0.9273998  -1.8101475
  -0.6138003 ]
 [-0.73491657 -0.4683098   0.98773897 ... -1.5353742  -0.46504074
  -0.7004199 ]
 ...
 [-1.2474755  -0.21696009  0.98941916 ... -0.26631796 -1.4040056
  -0.40795743]
 [-1.2279369  -0.19058605  0.9209532  ...  0.44441038 -0.45189548
  -0.44402114]
 [-1.2453235  -0.1878295   0.8509267  ...  0.16132051 -1.1429096
  -0.4791148 ]]
['[SIL]' 'F' 'AO' 'R' 'N' 'AA' 'T' 'IY' 'V' 'IH' 'N' 'AH' 'B' 'R' 'UH' 'K'
 '[SIL]' 'K' 'UH' 'D' 'R' 'AH' 'N' 'P' 'AE' 'S' 'T' 'M' 'IH' 'S' 'IH' 'Z'
 'R' 'EY' 'CH' 'AH' 'L' 'IH' 'N' 'D' 'Z' 'D' 'AO' 'R' 'W' 'IH' 'TH' 'AW'
 'T' 'D' 'UW' 'R' 'AH' 'G' 'AA' 'R' 'D' 'F' 'AO' 'R' 'D' 'IY' 'S' 'AH' 'N'
 'S' 'IY' 'AH' 'N' 'D' 'IH' 'K' 'AO' 'R' 'AH' 'M' '[SIL]' 'IH' 'T' 'P' 'R'
 'AA' 'B' 'AH' 'B' 'L' 'IY' 'W' 'AA' 'Z' 'K' 'AA' 'N' 'SH' 'AH' 'S' 'DH'
 'AE' 'T' 'M' 'IH' 'S' 'IH' 'Z' 'R' 'EY' 'CH' 'AH' 'L' 'W' 'AA' 'Z' 'S'
 'IH' 'T' 'IH' 'NG' 'AE' 'T' 'HH' 'ER' 'W' 'IH' 'N' 'D' 'OW' '[SIL]' 'K'
 'IY' 'P' 'IH' 'NG' 'AH' 'SH' 'AA' 'R' 'P' 'AY' 'AA' 'N' 'EH' 'V' 'R' 'IY'
 'TH' 'IH' 'NG' 'DH' 'AE' 'T' 'P' 'AE' 'S' 'T' '[SIL]' 'F' 'R' 'AH' 'M'
 'B' 'R' 'UH' 'K' 'S' 'AH' 'N' 'D' 'CH' 'IH' 'L' 'D' 'R' 'AH' 'N' 'AH' 'P'
 '[SIL]']

In [ ]:
yep = np.concatenate(labels, axis=0)
print(yep.shape)

(3717031,)

In [ ]:
print(yep[146])

DH

In [ ]:
PHONEME_MAP = {}
for i in range(len(PHONEMES)):
    PHONEME_MAP[PHONEMES[i]] = i

print(PHONEME_MAP)

{'': 0, 'AA': 1, 'AE': 2, 'AH': 3, 'AO': 4, 'AW': 5, 'AY': 6, 'B': 7, 'CH': 8, 'D': 9, 'DH': 10, 'EH': 11, 'ER': 12, 'EY': 13, 'F': 14, 'G': 15, 'HH': 16, 'IH': 17, 'IY': 18, 'JH': 19, 'K': 20, 'L': 21, 'M': 22, 'N': 23, 'NG': 24, 'OW': 25, 'OY': 26, 'P': 27, 'R': 28, 'S': 29, 'SH': 30, 'T': 31, 'TH': 32, 'UH': 33, 'UW': 34, 'V': 35, 'W': 36, 'Y': 37, 'Z': 38, 'ZH': 39, '[SIL]': 40}

In [ ]:
labels_mapped = []
for i in range(len(labels)):
    labels_mapped.append([PHONEME_MAP[j] for j in labels[i]])
print(labels[0])
print(labels_mapped[0])

['[SIL]' 'CH' 'AE' 'P' 'T' 'ER' 'W' 'AH' 'N' '[SIL]' 'M' 'IH' 'S' 'IH' 'Z'
 'R' 'EY' 'CH' 'AH' 'L' 'IH' 'N' 'D' 'IH' 'Z' 'S' 'ER' 'P' 'R' 'AY' 'Z'
 'D' '[SIL]' 'M' 'IH' 'S' 'IH' 'Z' 'R' 'EY' 'CH' 'AH' 'L' 'IH' 'N' 'D'
 '[SIL]' 'L' 'AY' 'V' 'D' '[SIL]' 'JH' 'AH' 'S' 'T' 'W' 'EH' 'R' 'DH' 'AH'
 'AE' 'V' 'AH' 'N' 'L' 'IY' 'AH' 'M' 'EY' 'N' 'R' 'OW' 'D' '[SIL]' 'D'
 'IH' 'P' 'T' '[SIL]' 'D' 'AW' 'N' 'IH' 'N' 'T' 'UW' 'AH' 'L' 'IH' 'T'
 'AH' 'L' 'HH' 'AA' 'L' 'OW' '[SIL]' 'F' 'R' 'IH' 'N' 'JH' 'D' 'W' 'IH'
 'DH' 'AA' 'L' 'D' 'ER' 'Z' 'AH' 'N' 'D' 'L' 'EY' 'D' 'IY' 'Z' 'IH' 'R'
 'D' 'R' 'AA' 'P' 'S' 'AH' 'N' 'D' 'T' 'R' 'AE' 'V' 'ER' 'S' 'T' 'B' 'AY'
 'AH' 'B' 'R' 'UH' 'K' '[SIL]']
[40, 8, 2, 27, 31, 12, 36, 3, 23, 40, 22, 17, 29, 17, 38, 28, 13, 8, 3, 21, 17, 23, 9, 17, 38, 29, 12, 27, 28, 6, 38, 9, 40, 22, 17, 29, 17, 38, 28, 13, 8, 3, 21, 17, 23, 9, 40, 21, 6, 35, 9, 40, 19, 3, 29, 31, 36, 11, 28, 10, 3, 2, 35, 3, 23, 21, 18, 3, 22, 13, 23, 28, 25, 9, 40, 9, 17, 27, 31, 40, 9, 5, 23, 17, 23, 31, 34, 3, 21, 17, 31, 3, 21, 16, 1, 21, 25, 40, 14, 28, 17, 23, 19, 9, 36, 17, 10, 1, 21, 9, 12, 38, 3, 23, 9, 21, 13, 9, 18, 38, 17, 28, 9, 28, 1, 27, 29, 3, 23, 9, 31, 28, 2, 35, 12, 29, 31, 7, 6, 3, 7, 28, 33, 20, 40]

### Train Data

In [ ]:
class AudioDataset(torch.utils.data.Dataset):

    # For this homework, we give you full flexibility to design your data set class.
    # Hint: The data from HW1 is very similar to this HW

    #TODO
    def __init__(self, root, partition= "train-clean-100", file_subset=None):
        '''
        Initializes the dataset.

        INPUTS: What inputs do you need here?
        '''
        self.root = root
        self.partition = partition
        self.file_subset = file_subset
        # Load the directory and all files in them

        self.mfcc_dir = os.path.join(self.root, self.partition, 'mfcc')
        self.transcript_dir = os.path.join(self.root, self.partition, 'transcript')

        # might as well load it in order
        # mfcc_name = os.listdir(self.mfcc_dir)
        # mfcc_name.sort()
        # transcript_name = os.listdir(self.transcript_dir)
        # transcript_name.sort()
        self.mfcc_files = sorted(os.listdir(self.mfcc_dir))
        self.transcript_files = sorted(os.listdir(self.transcript_dir))

        self.PHONEMES = PHONEMES

        #TODO
        # WHAT SHOULD THE LENGTH OF THE DATASET BE?
        self.length = len(self.mfcc_files)
        assert len(self.mfcc_files) == len(self.transcript_files)

        #TODO
        # HOW CAN WE REPRESENT PHONEMES? CAN WE CREATE A MAPPING FOR THEM?
        # HINT: TENSORS CANNOT STORE NON-NUMERICAL VALUES OR STRINGS
        self.PHONEME_MAP = {}
        for i in range(len(self.PHONEMES)):
            self.PHONEME_MAP[self.PHONEMES[i]] = i


        #TODO
        # CREATE AN ARRAY OF ALL FEATUERS AND LABELS
        # WHAT NORMALIZATION TECHNIQUE DID YOU USE IN HW1? CAN WE USE IT HERE?
        self.mfccs = []
        self.transcripts = []

        for i in range(len(self.mfcc_files)):
            mfcc = np.load(os.path.join(self.mfcc_dir, self.mfcc_files[i]))
            transcript = np.load(os.path.join(self.transcript_dir, self.transcript_files[i]))

            mfcc = (mfcc - np.mean(mfcc, axis=0, keepdims=True))/(np.std(mfcc, axis=0, keepdims=True) + 1e-5)
            transcript = transcript[1:-1]

            self.mfccs.append(torch.tensor(mfcc, dtype=torch.float32))
            self.transcripts.append(transcript)

        self.transcripts_mapped = []
        for i in range(len(self.transcripts)):
            self.transcripts_mapped.append(torch.tensor([self.PHONEME_MAP[j] for j in self.transcripts[i]]))

        '''
        You may decide to do this in __getitem__ if you wish.
        However, doing this here will make the __init__ function take the load of
        loading the data, and shift it away from training.
        '''


    def __len__(self):

        '''
        TODO: What do we return here?
        '''
        return self.length

    def __getitem__(self, ind):
        '''
        TODO: RETURN THE MFCC COEFFICIENTS AND ITS CORRESPONDING LABELS

        If you didn't do the loading and processing of the data in __init__,
        do that here.

        Once done, return a tuple of features and labels.
        '''
        mfcc = self.mfccs[ind]
        transcript = self.transcripts_mapped[ind]
        return mfcc, transcript


    def collate_fn(self,batch):
        '''
        TODO:
        1.  Extract the features and labels from 'batch'
        2.  We will additionally need to pad both features and labels,
            look at pytorch's docs for pad_sequence
        3.  This is a good place to perform transforms, if you so wish.
            Performing them on batches will speed the process up a bit.
        4.  Return batch of features, labels, lenghts of features,
            and lengths of labels.
        '''
        # batch of input mfcc coefficients
        batch_mfcc = [item[0] for item in batch]
        # batch of output phonemes
        batch_transcript = [item[1] for item in batch]

        # HINT: CHECK OUT -> pad_sequence (imported above)
        # Also be sure to check the input format (batch_first)
        batch_mfcc_pad = pad_sequence(batch_mfcc, batch_first=True, padding_value=0.0)
        lengths_mfcc = [len(mfcc) for mfcc in batch_mfcc]

        batch_transcript_pad = pad_sequence(batch_transcript, batch_first=True, padding_value=-1.0)
        lengths_transcript = [len(transcript) for transcript in batch_transcript]

        # You may apply some transformation, Time and Frequency masking, here in the collate function;
        # Food for thought -> Why are we applying the transformation here and not in the __getitem__?
        #                  -> Would we apply transformation on the validation set as well?
        #                  -> Is the order of axes / dimensions as expected for the transform functions?
        if self.partition == 'train-clean-100':
            batch_mfcc_pad = self.apply_spec_augment(batch_mfcc_pad,time_mask_param=10, freq_mask_param=8)
        # Return the following values: padded features, padded labels, actual length of features, actual length of the labels
        return batch_mfcc_pad, batch_transcript_pad, torch.tensor(lengths_mfcc), torch.tensor(lengths_transcript)

    def apply_spec_augment(self, mfcc_batch, time_mask_param=10, freq_mask_param=8):
        """
        Applies SpecAugment to a batch of MFCCs.
        Arguments:
        - mfcc_batch: Tensor of shape (batch_size, time_steps, freq_bins)
        - time_mask_param: Max time steps to mask
        - freq_mask_param: Max frequency bins to mask
        """
        batch_size, time_steps, freq_bins = mfcc_batch.shape

        # Apply time masking
        for i in range(batch_size):
            t = random.randint(0, time_mask_param)
            t0 = random.randint(0, max(1, time_steps - t))
            mfcc_batch[i, t0:t0 + t, :] = 0

        # Apply frequency masking
        for i in range(batch_size):
            f = random.randint(0, freq_mask_param)
            f0 = random.randint(0, max(1, freq_bins - f))
            mfcc_batch[i, :, f0:f0 + f] = 0

        return mfcc_batch

### Test Data

In [ ]:
# Test Dataloader
#TODO
class AudioDatasetTest(torch.utils.data.Dataset):
    def __init__(self, root, partition= "test-clean"):
        '''
        Initializes the dataset.
        '''
        self.root = root
        self.partition = partition
        # Load the directory and all files in them

        self.mfcc_dir = os.path.join(self.root, self.partition, 'mfcc')
        self.mfcc_names = sorted(os.listdir(self.mfcc_dir))

        self.mfccs = []

        for i in range(len(self.mfcc_names)):
            mfcc = np.load(os.path.join(self.mfcc_dir, self.mfcc_names[i]))
            mfcc = (mfcc - np.mean(mfcc, axis=0, keepdims=True))/(np.std(mfcc, axis=0, keepdims=True) + 1e-5)
            print(mfcc.shape)
            self.mfccs.append(torch.tensor(mfcc, dtype=torch.float32))

        self.length = len(self.mfccs)

    def __len__(self):
        '''
        TODO: What do we return here?
        '''
        return self.length

    def __getitem__(self, ind):
        '''
        TODO: RETURN THE MFCC COEFFICIENTS
        '''
        mfcc = self.mfccs[ind]
        return mfcc

    def collate_fn(self,batch):
        '''
        TODO:
        1.  Extract the features and labels from 'batch'
        2.  We will additionally need to pad both features and labels,
            look at pytorch's docs for pad_sequence
        3.  This is a good place to perform transforms, if you so wish.
            Performing them on batches will speed the process up a bit.
        4.  Return batch of features, labels, lenghts of features,
            and lengths of labels.
        '''
        # batch of input mfcc coefficients
        batch_mfcc = [item for item in batch]

        # HINT: CHECK OUT -> pad_sequence (imported above)
        # Also be sure to check the input format (batch_first)
        batch_mfcc_pad = pad_sequence(batch_mfcc, batch_first=True, padding_value=0.0)
        lengths_mfcc = [len(mfcc) for mfcc in batch_mfcc]

        # You may apply some transformation, Time and Frequency masking, here in the collate function;
        # Food for thought -> Why are we applying the transformation here and not in the __getitem__?
        #                  -> Would we apply transformation on the validation set as well?
        #                  -> Is the order of axes / dimensions as expected for the transform functions?

        # Return the following values: padded features, padded labels, actual length of features, actual length of the labels
        return batch_mfcc_pad, torch.tensor(lengths_mfcc)

### Config - Hyperparameters

In [ ]:
root = '/content/11-785-f24-hw3p2/'

# Feel free to add more items here
config = {
    "beam_width" : 3,
    "lr"         : 2e-3,
    "epochs"     : 60,
    "batch_size" : 64  # Increase if your device can handle it
}

# You may pass this as a parameter to the dataset class above
# This will help modularize your implementation
transforms = [] # set of tranformations

### Data loaders

In [ ]:
# get me RAMMM!!!!
import gc
gc.collect()

0

In [ ]:
# Create objects for the dataset class
train_data = AudioDataset(root='/content/11785-f24-hw3p2', partition='train-clean-100')
val_data = AudioDataset(root='/content/11785-f24-hw3p2', partition='dev-clean')
test_data = AudioDatasetTest(root='/content/11785-f24-hw3p2', partition='test-clean')

# import random
# from torch.utils.data import Subset

# train_subset_size = int(1* len(train_data))
# val_subset_size = int(1 * len(val_data))

# train_subset_indices = random.sample(range(len(train_data)), train_subset_size)
# val_subset_indices = random.sample(range(len(val_data)), val_subset_size)

# train_data_sub = Subset(train_data, train_subset_indices)
# val_data_sub = Subset(val_data, val_subset_indices)

# Do NOT forget to pass in the collate function as parameter while creating the dataloader
train_loader = torch.utils.data.DataLoader(
    dataset=train_data,
    num_workers=4,
    batch_size=config['batch_size'],
    shuffle=True,
    collate_fn=train_data.collate_fn)
val_loader = torch.utils.data.DataLoader(
    dataset=val_data,
    num_workers=4,
    batch_size=config['batch_size'],
    shuffle=False,
    collate_fn=val_data.collate_fn)
test_loader = torch.utils.data.DataLoader(
    dataset=test_data,
    num_workers=4,
    batch_size=config['batch_size'],
    shuffle=False,
    collate_fn=test_data.collate_fn)

print("Batch size: ", config['batch_size'])
print("Train dataset samples = {}, batches = {}".format(train_data.__len__(), len(train_loader)))
print("Val dataset samples = {}, batches = {}".format(val_data.__len__(), len(val_loader)))
print("Test dataset samples = {}, batches = {}".format(test_data.__len__(), len(test_loader)))

(1039, 28)
(323, 28)
(658, 28)
(264, 28)
(517, 28)
(959, 28)
(1051, 28)
(423, 28)
(669, 28)
(1053, 28)
(436, 28)
(1240, 28)
(1160, 28)
(787, 28)
(218, 28)
(577, 28)
(350, 28)
(883, 28)
(1568, 28)
(1385, 28)
(1675, 28)
(651, 28)
(1113, 28)
(1323, 28)
(1161, 28)
(657, 28)
(397, 28)
(267, 28)
(779, 28)
(463, 28)
(267, 28)
(657, 28)
(405, 28)
(329, 28)
(577, 28)
(340, 28)
(321, 28)
(517, 28)
(204, 28)
(537, 28)
(1156, 28)
(213, 28)
(513, 28)
(532, 28)
(585, 28)
(340, 28)
(1494, 28)
(2001, 28)
(315, 28)
(1997, 28)
(1499, 28)
(1629, 28)
(471, 28)
(335, 28)
(902, 28)
(1165, 28)
(305, 28)
(311, 28)
(395, 28)
(1333, 28)
(559, 28)
(769, 28)
(217, 28)
(796, 28)
(1068, 28)
(900, 28)
(1792, 28)
(1257, 28)
(1061, 28)
(852, 28)
(236, 28)
(1420, 28)
(2071, 28)
(2302, 28)
(605, 28)
(1515, 28)
(1461, 28)
(298, 28)
(435, 28)
(1604, 28)
(1655, 28)
(457, 28)
(1150, 28)
(1389, 28)
(1022, 28)
(1398, 28)
(959, 28)
(2363, 28)
(1520, 28)
(741, 28)
(2008, 28)
(1120, 28)
(1896, 28)
(366, 28)
(187, 28)
(421, 28)
(1094, 28)
(658, 28)
(2086, 28)
(288, 28)
(793, 28)
(1447, 28)
(532, 28)
(658, 28)
(319, 28)
(1003, 28)
(262, 28)
(484, 28)
(1850, 28)
(842, 28)
(588, 28)
(437, 28)
(671, 28)
(398, 28)
(306, 28)
(385, 28)
(669, 28)
(495, 28)
(722, 28)
(977, 28)
(399, 28)
(400, 28)
(245, 28)
(312, 28)
(1765, 28)
(183, 28)
(1724, 28)
(2346, 28)
(1625, 28)
(1735, 28)
(2535, 28)
(3000, 28)
(1078, 28)
(946, 28)
(983, 28)
(498, 28)
(745, 28)
(768, 28)
(207, 28)
(578, 28)
(468, 28)
(575, 28)
(272, 28)
(225, 28)
(281, 28)
(574, 28)
(479, 28)
(585, 28)
(221, 28)
(292, 28)
(199, 28)
(265, 28)
(273, 28)
(348, 28)
(1431, 28)
(196, 28)
(503, 28)
(1087, 28)
(1441, 28)
(1602, 28)
(749, 28)
(1383, 28)
(671, 28)
(727, 28)
(213, 28)
(1072, 28)
(313, 28)
(231, 28)
(737, 28)
(1411, 28)
(411, 28)
(1239, 28)
(1667, 28)
(478, 28)
(1368, 28)
(740, 28)
(1660, 28)
(1137, 28)
(875, 28)
(1074, 28)
(1015, 28)
(1501, 28)
(2130, 28)
(1618, 28)
(360, 28)
(471, 28)
(259, 28)
(2481, 28)
(1339, 28)
(1608, 28)
(1859, 28)
(1905, 28)
(582, 28)
(2052, 28)
(1273, 28)
(305, 28)
(1330, 28)
(816, 28)
(1647, 28)
(1384, 28)
(1194, 28)
(703, 28)
(281, 28)
(1521, 28)
(1668, 28)
(1112, 28)
(374, 28)
(330, 28)
(1268, 28)
(1435, 28)
(1623, 28)
(581, 28)
(808, 28)
(771, 28)
(764, 28)
(479, 28)
(424, 28)
(651, 28)
(682, 28)
(622, 28)
(1045, 28)
(624, 28)
(859, 28)
(423, 28)
(484, 28)
(366, 28)
(362, 28)
(579, 28)
(209, 28)
(1064, 28)
(1196, 28)
(1498, 28)
(583, 28)
(980, 28)
(284, 28)
(557, 28)
(522, 28)
(866, 28)
(825, 28)
(323, 28)
(600, 28)
(529, 28)
(1618, 28)
(478, 28)
(574, 28)
(392, 28)
(1139, 28)
(379, 28)
(446, 28)
(711, 28)
(381, 28)
(1136, 28)
(400, 28)
(604, 28)
(520, 28)
(639, 28)
(771, 28)
(847, 28)
(1262, 28)
(788, 28)
(507, 28)
(947, 28)
(1173, 28)
(312, 28)
(316, 28)
(669, 28)
(266, 28)
(849, 28)
(1023, 28)
(1507, 28)
(2010, 28)
(1279, 28)
(2329, 28)
(1011, 28)
(1413, 28)
(1344, 28)
(948, 28)
(742, 28)
(982, 28)
(638, 28)
(587, 28)
(480, 28)
(550, 28)
(783, 28)
(384, 28)
(1015, 28)
(1365, 28)
(1045, 28)
(651, 28)
(347, 28)
(634, 28)
(345, 28)
(779, 28)
(1401, 28)
(1354, 28)
(624, 28)
(1222, 28)
(436, 28)
(561, 28)
(1848, 28)
(414, 28)
(766, 28)
(996, 28)
(972, 28)
(755, 28)
(1071, 28)
(486, 28)
(508, 28)
(1004, 28)
(561, 28)
(965, 28)
(819, 28)
(885, 28)
(529, 28)
(381, 28)
(777, 28)
(751, 28)
(632, 28)
(518, 28)
(564, 28)
(1595, 28)
(783, 28)
(394, 28)
(624, 28)
(1124, 28)
(1100, 28)
(944, 28)
(1818, 28)
(1233, 28)
(714, 28)
(220, 28)
(701, 28)
(793, 28)
(411, 28)
(890, 28)
(1021, 28)
(609, 28)
(651, 28)
(447, 28)
(270, 28)
(1081, 28)
(452, 28)
(426, 28)
(700, 28)
(528, 28)
(278, 28)
(702, 28)
(428, 28)
(281, 28)
(494, 28)
(421, 28)
(224, 28)
(263, 28)
(266, 28)
(509, 28)
(367, 28)
(325, 28)
(329, 28)
(444, 28)
(386, 28)
(473, 28)
(518, 28)
(254, 28)
(1001, 28)
(344, 28)
(621, 28)
(409, 28)
(741, 28)
(695, 28)
(494, 28)
(394, 28)
(569, 28)
(749, 28)
(368, 28)
(371, 28)
(353, 28)
(582, 28)
(270, 28)
(546, 28)
(432, 28)
(349, 28)
(256, 28)
(274, 28)
(380, 28)
(304, 28)
(194, 28)
(341, 28)
(397, 28)
(457, 28)
(322, 28)
(586, 28)
(406, 28)
(896, 28)
(247, 28)
(209, 28)
(198, 28)
(675, 28)
(464, 28)
(443, 28)
(496, 28)
(244, 28)
(218, 28)
(393, 28)
(343, 28)
(592, 28)
(196, 28)
(330, 28)
(308, 28)
(282, 28)
(397, 28)
(202, 28)
(869, 28)
(914, 28)
(233, 28)
(695, 28)
(332, 28)
(261, 28)
(803, 28)
(210, 28)
(643, 28)
(495, 28)
(696, 28)
(445, 28)
(259, 28)
(243, 28)
(292, 28)
(291, 28)
(484, 28)
(594, 28)
(795, 28)
(502, 28)
(202, 28)
(285, 28)
(358, 28)
(231, 28)
(521, 28)
(922, 28)
(753, 28)
(274, 28)
(944, 28)
(1013, 28)
(456, 28)
(305, 28)
(299, 28)
(508, 28)
(241, 28)
(702, 28)
(285, 28)
(753, 28)
(240, 28)
(890, 28)
(614, 28)
(873, 28)
(246, 28)
(351, 28)
(586, 28)
(610, 28)
(497, 28)
(521, 28)
(608, 28)
(1137, 28)
(470, 28)
(810, 28)
(505, 28)
(325, 28)
(1541, 28)
(891, 28)
(596, 28)
(227, 28)
(792, 28)
(3387, 28)
(1086, 28)
(767, 28)
(339, 28)
(694, 28)
(667, 28)
(2441, 28)
(466, 28)
(365, 28)
(526, 28)
(900, 28)
(382, 28)
(869, 28)
(275, 28)
(732, 28)
(632, 28)
(259, 28)
(291, 28)
(876, 28)
(191, 28)
(372, 28)
(344, 28)
(333, 28)
(820, 28)
(315, 28)
(1242, 28)
(444, 28)
(715, 28)
(306, 28)
(1278, 28)
(534, 28)
(317, 28)
(305, 28)
(337, 28)
(1692, 28)
(534, 28)
(946, 28)
(805, 28)
(666, 28)
(230, 28)
(554, 28)
(2253, 28)
(799, 28)
(1548, 28)
(1463, 28)
(260, 28)
(905, 28)
(1378, 28)
(266, 28)
(3161, 28)
(1436, 28)
(3057, 28)
(1622, 28)
(1609, 28)
(1421, 28)
(1295, 28)
(1497, 28)
(222, 28)
(279, 28)
(311, 28)
(262, 28)
(239, 28)
(529, 28)
(224, 28)
(514, 28)
(523, 28)
(355, 28)
(278, 28)
(559, 28)
(680, 28)
(848, 28)
(1608, 28)
(274, 28)
(320, 28)
(1282, 28)
(795, 28)
(353, 28)
(687, 28)
(1045, 28)
(2021, 28)
(624, 28)
(234, 28)
(138, 28)
(241, 28)
(731, 28)
(348, 28)
(296, 28)
(186, 28)
(217, 28)
(635, 28)
(608, 28)
(400, 28)
(527, 28)
(649, 28)
(335, 28)
(564, 28)
(261, 28)
(380, 28)
(1004, 28)
(489, 28)
(997, 28)
(267, 28)
(504, 28)
(1459, 28)
(1307, 28)
(1672, 28)
(1987, 28)
(686, 28)
(408, 28)
(1340, 28)
(908, 28)
(956, 28)
(1078, 28)
(1583, 28)
(1110, 28)
(1385, 28)
(371, 28)
(883, 28)
(1997, 28)
(1987, 28)
(1250, 28)
(1478, 28)
(1031, 28)
(1091, 28)
(1362, 28)
(1102, 28)
(473, 28)
(1524, 28)
(1755, 28)
(858, 28)
(2590, 28)
(638, 28)
(994, 28)
(1654, 28)
(1165, 28)
(1756, 28)
(856, 28)
(2545, 28)
(704, 28)
(792, 28)
(557, 28)
(234, 28)
(541, 28)
(371, 28)
(1325, 28)
(1192, 28)
(888, 28)
(652, 28)
(325, 28)
(647, 28)
(611, 28)
(864, 28)
(382, 28)
(393, 28)
(620, 28)
(667, 28)
(441, 28)
(677, 28)
(675, 28)
(930, 28)
(421, 28)
(617, 28)
(405, 28)
(708, 28)
(220, 28)
(432, 28)
(500, 28)
(663, 28)
(962, 28)
(371, 28)
(406, 28)
(734, 28)
(1135, 28)
(1272, 28)
(678, 28)
(1090, 28)
(435, 28)
(199, 28)
(226, 28)
(293, 28)
(283, 28)
(499, 28)
(362, 28)
(405, 28)
(366, 28)
(651, 28)
(1004, 28)
(906, 28)
(475, 28)
(609, 28)
(177, 28)
(503, 28)
(313, 28)
(218, 28)
(235, 28)
(418, 28)
(235, 28)
(372, 28)
(218, 28)
(395, 28)
(331, 28)
(1089, 28)
(1052, 28)
(421, 28)
(1077, 28)
(312, 28)
(214, 28)
(1280, 28)
(282, 28)
(214, 28)
(508, 28)
(512, 28)
(302, 28)
(437, 28)
(159, 28)
(301, 28)
(323, 28)
(448, 28)
(202, 28)
(274, 28)
(1057, 28)
(498, 28)
(631, 28)
(303, 28)
(251, 28)
(656, 28)
(706, 28)
(239, 28)
(459, 28)
(399, 28)
(888, 28)
(253, 28)
(700, 28)
(303, 28)
(994, 28)
(733, 28)
(342, 28)
(477, 28)
(736, 28)
(451, 28)
(369, 28)
(575, 28)
(253, 28)
(421, 28)
(239, 28)
(469, 28)
(294, 28)
(517, 28)
(696, 28)
(393, 28)
(563, 28)
(1186, 28)
(302, 28)
(251, 28)
(319, 28)
(583, 28)
(300, 28)
(916, 28)
(690, 28)
(713, 28)
(742, 28)
(450, 28)
(749, 28)
(502, 28)
(300, 28)
(504, 28)
(721, 28)
(886, 28)
(427, 28)
(1251, 28)
(484, 28)
(1116, 28)
(547, 28)
(339, 28)
(995, 28)
(894, 28)
(350, 28)
(1134, 28)
(176, 28)
(2114, 28)
(482, 28)
(518, 28)
(320, 28)
(291, 28)
(286, 28)
(267, 28)
(366, 28)
(234, 28)
(1455, 28)
(1340, 28)
(1600, 28)
(626, 28)
(257, 28)
(212, 28)
(170, 28)
(1467, 28)
(354, 28)
(1198, 28)
(306, 28)
(267, 28)
(334, 28)
(370, 28)
(307, 28)
(827, 28)
(483, 28)
(520, 28)
(343, 28)
(377, 28)
(616, 28)
(485, 28)
(303, 28)
(360, 28)
(659, 28)
(495, 28)
(608, 28)
(1608, 28)
(427, 28)
(804, 28)
(190, 28)
(206, 28)
(451, 28)
(1463, 28)
(940, 28)
(831, 28)
(332, 28)
(941, 28)
(358, 28)
(369, 28)
(390, 28)
(198, 28)
(244, 28)
(377, 28)
(641, 28)
(637, 28)
(1015, 28)
(480, 28)
(384, 28)
(648, 28)
(548, 28)
(338, 28)
(410, 28)
(248, 28)
(264, 28)
(233, 28)
(362, 28)
(338, 28)
(697, 28)
(342, 28)
(287, 28)
(323, 28)
(612, 28)
(389, 28)
(875, 28)
(144, 28)
(223, 28)
(350, 28)
(903, 28)
(521, 28)
(844, 28)
(718, 28)
(267, 28)
(293, 28)
(329, 28)
(572, 28)
(638, 28)
(550, 28)
(515, 28)
(258, 28)
(485, 28)
(298, 28)
(193, 28)
(345, 28)
(347, 28)
(280, 28)
(782, 28)
(1040, 28)
(338, 28)
(743, 28)
(640, 28)
(484, 28)
(497, 28)
(1004, 28)
(729, 28)
(531, 28)
(803, 28)
(265, 28)
(178, 28)
(263, 28)
(708, 28)
(540, 28)
(537, 28)
(284, 28)
(647, 28)
(604, 28)
(809, 28)
(496, 28)
(551, 28)
(369, 28)
(392, 28)
(481, 28)
(1652, 28)
(566, 28)
(575, 28)
(477, 28)
(2714, 28)
(821, 28)
(1531, 28)
(1727, 28)
(818, 28)
(1031, 28)
(1568, 28)
(760, 28)
(1541, 28)
(1182, 28)
(2042, 28)
(2083, 28)
(685, 28)
(1053, 28)
(873, 28)
(779, 28)
(772, 28)
(783, 28)
(834, 28)
(1209, 28)
(984, 28)
(1574, 28)
(738, 28)
(462, 28)
(914, 28)
(1995, 28)
(469, 28)
(1144, 28)
(373, 28)
(456, 28)
(846, 28)
(711, 28)
(566, 28)
(779, 28)
(777, 28)
(1297, 28)
(508, 28)
(952, 28)
(677, 28)
(777, 28)
(969, 28)
(525, 28)
(1221, 28)
(608, 28)
(490, 28)
(2594, 28)
(1204, 28)
(563, 28)
(1057, 28)
(1898, 28)
(529, 28)
(836, 28)
(1446, 28)
(1050, 28)
(945, 28)
(1256, 28)
(1296, 28)
(1099, 28)
(316, 28)
(557, 28)
(1121, 28)
(839, 28)
(1411, 28)
(829, 28)
(777, 28)
(371, 28)
(1399, 28)
(1051, 28)
(425, 28)
(479, 28)
(1467, 28)
(776, 28)
(531, 28)
(1056, 28)
(1999, 28)
(743, 28)
(971, 28)
(680, 28)
(498, 28)
(462, 28)
(822, 28)
(1472, 28)
(460, 28)
(1050, 28)
(791, 28)
(1137, 28)
(1669, 28)
(747, 28)
(2507, 28)
(466, 28)
(1298, 28)
(412, 28)
(946, 28)
(722, 28)
(882, 28)
(753, 28)
(819, 28)
(295, 28)
(207, 28)
(755, 28)
(306, 28)
(730, 28)
(826, 28)
(773, 28)
(1351, 28)
(669, 28)
(475, 28)
(697, 28)
(581, 28)
(913, 28)
(664, 28)
(1438, 28)
(165, 28)
(1269, 28)
(288, 28)
(611, 28)
(860, 28)
(414, 28)
(578, 28)
(905, 28)
(1221, 28)
(916, 28)
(1669, 28)
(454, 28)
(549, 28)
(601, 28)
(890, 28)
(396, 28)
(299, 28)
(846, 28)
(345, 28)
(933, 28)
(2823, 28)
(1416, 28)
(1149, 28)
(1268, 28)
(686, 28)
(1397, 28)
(1217, 28)
(1896, 28)
(968, 28)
(648, 28)
(2560, 28)
(648, 28)
(551, 28)
(267, 28)
(636, 28)
(487, 28)
(296, 28)
(1190, 28)
(796, 28)
(1181, 28)
(333, 28)
(1113, 28)
(1215, 28)
(874, 28)
(2144, 28)
(1642, 28)
(1850, 28)
(2370, 28)
(1245, 28)
(2382, 28)
(1827, 28)
(271, 28)
(733, 28)
(282, 28)
(326, 28)
(567, 28)
(257, 28)
(415, 28)
(1795, 28)
(617, 28)
(326, 28)
(1317, 28)
(292, 28)
(827, 28)
(814, 28)
(547, 28)
(296, 28)
(465, 28)
(296, 28)
(522, 28)
(856, 28)
(280, 28)
(436, 28)
(1360, 28)
(2853, 28)
(1885, 28)
(2061, 28)
(520, 28)
(585, 28)
(573, 28)
(878, 28)
(1062, 28)
(1085, 28)
(1512, 28)
(416, 28)
(694, 28)
(2033, 28)
(1256, 28)
(952, 28)
(870, 28)
(971, 28)
(1668, 28)
(1664, 28)
(1957, 28)
(1302, 28)
(1718, 28)
(1051, 28)
(1211, 28)
(668, 28)
(1138, 28)
(1197, 28)
(427, 28)
(1257, 28)
(1343, 28)
(1447, 28)
(505, 28)
(2607, 28)
(288, 28)
(1025, 28)
(1966, 28)
(474, 28)
(373, 28)
(1774, 28)
(564, 28)
(494, 28)
(1780, 28)
(1270, 28)
(1391, 28)
(1987, 28)
(761, 28)
(1191, 28)
(1409, 28)
(2205, 28)
(1283, 28)
(1093, 28)
(2216, 28)
(1185, 28)
(345, 28)
(631, 28)
(234, 28)
(366, 28)
(1197, 28)
(335, 28)
(286, 28)
(206, 28)
(545, 28)
(778, 28)
(309, 28)
(390, 28)
(374, 28)
(436, 28)
(530, 28)
(255, 28)
(1016, 28)
(1222, 28)
(567, 28)
(378, 28)
(751, 28)
(352, 28)
(228, 28)
(222, 28)
(312, 28)
(895, 28)
(462, 28)
(325, 28)
(779, 28)
(539, 28)
(408, 28)
(290, 28)
(305, 28)
(767, 28)
(397, 28)
(1240, 28)
(275, 28)
(294, 28)
(258, 28)
(235, 28)
(446, 28)
(960, 28)
(270, 28)
(336, 28)
(307, 28)
(270, 28)
(521, 28)
(582, 28)
(606, 28)
(478, 28)
(479, 28)
(191, 28)
(372, 28)
(536, 28)
(326, 28)
(284, 28)
(175, 28)
(779, 28)
(326, 28)
(355, 28)
(611, 28)
(308, 28)
(630, 28)
(462, 28)
(763, 28)
(202, 28)
(207, 28)
(440, 28)
(350, 28)
(893, 28)
(409, 28)
(205, 28)
(369, 28)
(239, 28)
(598, 28)
(361, 28)
(247, 28)
(294, 28)
(726, 28)
(243, 28)
(227, 28)
(489, 28)
(268, 28)
(501, 28)
(324, 28)
(376, 28)
(235, 28)
(212, 28)
(545, 28)
(295, 28)
(353, 28)
(624, 28)
(262, 28)
(301, 28)
(320, 28)
(702, 28)
(304, 28)
(403, 28)
(286, 28)
(205, 28)
(449, 28)
(186, 28)
(692, 28)
(471, 28)
(536, 28)
(584, 28)
(257, 28)
(259, 28)
(255, 28)
(1128, 28)
(314, 28)
(485, 28)
(209, 28)
(417, 28)
(207, 28)
(259, 28)
(355, 28)
(1126, 28)
(1512, 28)
(557, 28)
(269, 28)
(1040, 28)
(607, 28)
(382, 28)
(1722, 28)
(1054, 28)
(333, 28)
(289, 28)
(2246, 28)
(1444, 28)
(616, 28)
(1203, 28)
(510, 28)
(917, 28)
(3157, 28)
(195, 28)
(322, 28)
(383, 28)
(1475, 28)
(1427, 28)
(2805, 28)
(550, 28)
(1123, 28)
(749, 28)
(539, 28)
(531, 28)
(384, 28)
(1538, 28)
(388, 28)
(293, 28)
(1033, 28)
(395, 28)
(215, 28)
(485, 28)
(455, 28)
(3491, 28)
(517, 28)
(587, 28)
(385, 28)
(613, 28)
(623, 28)
(805, 28)
(427, 28)
(718, 28)
(630, 28)
(457, 28)
(307, 28)
(616, 28)
(299, 28)
(1188, 28)
(1069, 28)
(1531, 28)
(371, 28)
(2212, 28)
(2956, 28)
(695, 28)
(354, 28)
(908, 28)
(1426, 28)
(1141, 28)
(867, 28)
(797, 28)
(423, 28)
(328, 28)
(219, 28)
(282, 28)
(967, 28)
(743, 28)
(554, 28)
(238, 28)
(618, 28)
(803, 28)
(282, 28)
(1387, 28)
(544, 28)
(998, 28)
(957, 28)
(461, 28)
(443, 28)
(1477, 28)
(300, 28)
(556, 28)
(260, 28)
(331, 28)
(464, 28)
(194, 28)
(322, 28)
(232, 28)
(690, 28)
(389, 28)
(1210, 28)
(268, 28)
(1232, 28)
(1982, 28)
(472, 28)
(386, 28)
(600, 28)
(379, 28)
(1089, 28)
(975, 28)
(1463, 28)
(385, 28)
(463, 28)
(1501, 28)
(657, 28)
(1198, 28)
(577, 28)
(471, 28)
(521, 28)
(684, 28)
(870, 28)
(660, 28)
(267, 28)
(308, 28)
(460, 28)
(802, 28)
(1070, 28)
(292, 28)
(400, 28)
(487, 28)
(835, 28)
(496, 28)
(418, 28)
(2169, 28)
(659, 28)
(449, 28)
(363, 28)
(445, 28)
(1427, 28)
(653, 28)
(654, 28)
(1038, 28)
(544, 28)
(2837, 28)
(558, 28)
(279, 28)
(727, 28)
(380, 28)
(451, 28)
(686, 28)
(892, 28)
(1315, 28)
(678, 28)
(540, 28)
(266, 28)
(976, 28)
(717, 28)
(861, 28)
(326, 28)
(865, 28)
(911, 28)
(471, 28)
(745, 28)
(819, 28)
(641, 28)
(1432, 28)
(827, 28)
(1770, 28)
(920, 28)
(366, 28)
(369, 28)
(1033, 28)
(1137, 28)
(1178, 28)
(431, 28)
(210, 28)
(780, 28)
(669, 28)
(598, 28)
(1517, 28)
(1240, 28)
(1572, 28)
(1085, 28)
(447, 28)
(445, 28)
(824, 28)
(1477, 28)
(469, 28)
(1135, 28)
(546, 28)
(2610, 28)
(1069, 28)
(1455, 28)
(1355, 28)
(541, 28)
(1602, 28)
(397, 28)
(547, 28)
(597, 28)
(736, 28)
(1384, 28)
(458, 28)
(1144, 28)
(1161, 28)
(289, 28)
(598, 28)
(469, 28)
(292, 28)
(303, 28)
(848, 28)
(413, 28)
(562, 28)
(284, 28)
(620, 28)
(226, 28)
(1241, 28)
(468, 28)
(1753, 28)
(816, 28)
(641, 28)
(2097, 28)
(1092, 28)
(394, 28)
(1737, 28)
(837, 28)
(751, 28)
(184, 28)
(850, 28)
(697, 28)
(227, 28)
(1367, 28)
(673, 28)
(478, 28)
(295, 28)
(2910, 28)
(624, 28)
(1271, 28)
(1279, 28)
(525, 28)
(196, 28)
(498, 28)
(363, 28)
(343, 28)
(217, 28)
(218, 28)
(619, 28)
(493, 28)
(207, 28)
(333, 28)
(341, 28)
(348, 28)
(455, 28)
(207, 28)
(320, 28)
(427, 28)
(212, 28)
(259, 28)
(390, 28)
(494, 28)
(327, 28)
(346, 28)
(473, 28)
(344, 28)
(530, 28)
(328, 28)
(303, 28)
(219, 28)
(371, 28)
(209, 28)
(272, 28)
(780, 28)
(974, 28)
(524, 28)
(657, 28)
(390, 28)
(422, 28)
(353, 28)
(414, 28)
(195, 28)
(277, 28)
(279, 28)
(605, 28)
(373, 28)
(481, 28)
(234, 28)
(370, 28)
(249, 28)
(392, 28)
(326, 28)
(284, 28)
(553, 28)
(584, 28)
(389, 28)
(570, 28)
(273, 28)
(303, 28)
(303, 28)
(318, 28)
(543, 28)
(257, 28)
(210, 28)
(286, 28)
(247, 28)
(326, 28)
(515, 28)
(217, 28)
(552, 28)
(419, 28)
(334, 28)
(535, 28)
(558, 28)
(387, 28)
(544, 28)
(704, 28)
(459, 28)
(614, 28)
(1538, 28)
(510, 28)
(425, 28)
(212, 28)
(267, 28)
(654, 28)
(2537, 28)
(430, 28)
(272, 28)
(464, 28)
(493, 28)
(237, 28)
(449, 28)
(1883, 28)
(1120, 28)
(575, 28)
(574, 28)
(1184, 28)
(361, 28)
(217, 28)
(229, 28)
(501, 28)
(352, 28)
(248, 28)
(2014, 28)
(1573, 28)
(1240, 28)
(887, 28)
(2708, 28)
(1243, 28)
(560, 28)
(800, 28)
(578, 28)
(217, 28)
(233, 28)
(408, 28)
(262, 28)
(855, 28)
(682, 28)
(768, 28)
(1098, 28)
(945, 28)
(584, 28)
(1537, 28)
(1202, 28)
(978, 28)
(1094, 28)
(1360, 28)
(1388, 28)
(880, 28)
(874, 28)
(1446, 28)
(2322, 28)
(1221, 28)
(726, 28)
(2224, 28)
(2838, 28)
(1739, 28)
(911, 28)
(1301, 28)
(1748, 28)
(1149, 28)
(1141, 28)
(1376, 28)
(1433, 28)
(1247, 28)
(1716, 28)
(215, 28)
(254, 28)
(274, 28)
(347, 28)
(732, 28)
(1008, 28)
(331, 28)
(602, 28)
(608, 28)
(985, 28)
(629, 28)
(631, 28)
(2147, 28)
(705, 28)
(257, 28)
(410, 28)
(302, 28)
(541, 28)
(260, 28)
(343, 28)
(508, 28)
(282, 28)
(918, 28)
(455, 28)
(417, 28)
(408, 28)
(326, 28)
(1322, 28)
(1499, 28)
(733, 28)
(822, 28)
(989, 28)
(393, 28)
(279, 28)
(484, 28)
(454, 28)
(541, 28)
(2081, 28)
(389, 28)
(786, 28)
(315, 28)
(270, 28)
(981, 28)
(343, 28)
(230, 28)
(471, 28)
(558, 28)
(223, 28)
(480, 28)
(888, 28)
(362, 28)
(1104, 28)
(930, 28)
(1117, 28)
(607, 28)
(1195, 28)
(675, 28)
(291, 28)
(509, 28)
(771, 28)
(917, 28)
(434, 28)
(1145, 28)
(836, 28)
(197, 28)
(1014, 28)
(1455, 28)
(740, 28)
(631, 28)
(650, 28)
(405, 28)
(413, 28)
(493, 28)
(233, 28)
(186, 28)
(486, 28)
(357, 28)
(293, 28)
(427, 28)
(384, 28)
(503, 28)
(289, 28)
(351, 28)
(349, 28)
(447, 28)
(825, 28)
(633, 28)
(257, 28)
(441, 28)
(744, 28)
(533, 28)
(368, 28)
(507, 28)
(236, 28)
(543, 28)
(506, 28)
(265, 28)
(463, 28)
(498, 28)
(598, 28)
(437, 28)
(488, 28)
(683, 28)
(531, 28)
(345, 28)
(564, 28)
(288, 28)
(424, 28)
(564, 28)
(419, 28)
(791, 28)
(289, 28)
(427, 28)
(201, 28)
(376, 28)
(391, 28)
(678, 28)
(274, 28)
(669, 28)
(273, 28)
(343, 28)
(351, 28)
(473, 28)
(298, 28)
(821, 28)
(554, 28)
(309, 28)
(261, 28)
(418, 28)
(782, 28)
(392, 28)
(352, 28)
(502, 28)
(178, 28)
(213, 28)
(369, 28)
(549, 28)
(251, 28)
(603, 28)
(611, 28)
(412, 28)
(379, 28)
(1047, 28)
(198, 28)
(229, 28)
(444, 28)
(211, 28)
(336, 28)
(300, 28)
(603, 28)
(309, 28)
(431, 28)
(336, 28)
(837, 28)
(433, 28)
(251, 28)
(456, 28)
(374, 28)
(498, 28)
(536, 28)
(393, 28)
(366, 28)
(719, 28)
(739, 28)
(543, 28)
(504, 28)
(651, 28)
(399, 28)
(320, 28)
(509, 28)
(309, 28)
(338, 28)
(444, 28)
(736, 28)
(674, 28)
(594, 28)
(1036, 28)
(662, 28)
(412, 28)
(403, 28)
(1509, 28)
(1358, 28)
(472, 28)
(1021, 28)
(322, 28)
(1391, 28)
(638, 28)
(3077, 28)
(272, 28)
(377, 28)
(250, 28)
(772, 28)
(866, 28)
(251, 28)
(441, 28)
(917, 28)
(478, 28)
(489, 28)
(407, 28)
(878, 28)
(411, 28)
(1896, 28)
(965, 28)
(409, 28)
(1065, 28)
(1392, 28)
(475, 28)
(257, 28)
(301, 28)
(453, 28)
(394, 28)
(396, 28)
(124, 28)
(507, 28)
(286, 28)
(532, 28)
(192, 28)
(876, 28)
(398, 28)
(508, 28)
(384, 28)
(1527, 28)
(374, 28)
(370, 28)
(1392, 28)
(467, 28)
(328, 28)
(651, 28)
(198, 28)
(481, 28)
(462, 28)
(424, 28)
(291, 28)
(421, 28)
(819, 28)
(518, 28)
(652, 28)
(443, 28)
(348, 28)
(331, 28)
(755, 28)
(263, 28)
(503, 28)
(1523, 28)
(299, 28)
(477, 28)
(1299, 28)
(398, 28)
(497, 28)
(623, 28)
(883, 28)
(790, 28)
(816, 28)
(869, 28)
(1165, 28)
(927, 28)
(303, 28)
(417, 28)
(710, 28)
(668, 28)
(715, 28)
(382, 28)
(470, 28)
(418, 28)
(310, 28)
(464, 28)
(425, 28)
(268, 28)
(361, 28)
(648, 28)
(408, 28)
(350, 28)
(707, 28)
(262, 28)
(508, 28)
(785, 28)
(407, 28)
(485, 28)
(490, 28)
(569, 28)
(460, 28)
(302, 28)
(325, 28)
(200, 28)
(487, 28)
(551, 28)
(568, 28)
(398, 28)
(601, 28)
(271, 28)
(551, 28)
(249, 28)
(246, 28)
(400, 28)
(473, 28)
(262, 28)
(213, 28)
(255, 28)
(318, 28)
(209, 28)
(253, 28)
(228, 28)
(645, 28)
(736, 28)
(287, 28)
(350, 28)
(456, 28)
(632, 28)
(1327, 28)
(1031, 28)
(890, 28)
(397, 28)
(840, 28)
(612, 28)
(588, 28)
(1624, 28)
(714, 28)
(1307, 28)
(978, 28)
(558, 28)
(1243, 28)
(715, 28)
(473, 28)
(448, 28)
(695, 28)
(235, 28)
(840, 28)
(738, 28)
(457, 28)
(257, 28)
(376, 28)
(538, 28)
(620, 28)
(779, 28)
(208, 28)
(528, 28)
(351, 28)
(890, 28)
(618, 28)
(247, 28)
(651, 28)
(541, 28)
(243, 28)
(435, 28)
(516, 28)
(346, 28)
(1418, 28)
(498, 28)
(2327, 28)
(1102, 28)

In [ ]:
print("Train dataset samples = {}, batches = {}".format(train_data_sub.__len__(), len(train_loader)))

Train dataset samples = 2853, batches = 45

In [ ]:
for i, data in enumerate(test_loader):
    x, lx = data
    print(x.shape, lx.shape)
    print(lx)
    break

torch.Size([64, 2001, 28]) torch.Size([64])
tensor([1039,  323,  658,  264,  517,  959, 1051,  423,  669, 1053,  436, 1240,
        1160,  787,  218,  577,  350,  883, 1568, 1385, 1675,  651, 1113, 1323,
        1161,  657,  397,  267,  779,  463,  267,  657,  405,  329,  577,  340,
         321,  517,  204,  537, 1156,  213,  513,  532,  585,  340, 1494, 2001,
         315, 1997, 1499, 1629,  471,  335,  902, 1165,  305,  311,  395, 1333,
         559,  769,  217,  796])

In [ ]:
# sanity check
for data in train_loader:
    x, y, lx, ly = data
    print(x.shape, y.shape, lx.shape, ly.shape)
    print(lx, ly)
    print(max(lx), max(ly))
    print(y[0])
    break

torch.Size([64, 1658, 28]) torch.Size([64, 203]) torch.Size([64]) torch.Size([64])
tensor([1439, 1379, 1568,  468, 1658, 1282, 1410, 1430, 1444, 1525, 1385, 1404,
        1271, 1169, 1516, 1434, 1390, 1358, 1261, 1322, 1522, 1538, 1499, 1622,
         829, 1056, 1250, 1348,  815, 1461,  404, 1651, 1560, 1351,  643, 1595,
        1365, 1073, 1528, 1591,  459,  226, 1559, 1420, 1448,  544, 1546, 1460,
        1230, 1637, 1369, 1610, 1589, 1034, 1510, 1609, 1385, 1512,  472, 1541,
         526, 1585, 1102, 1585]) tensor([132, 131, 169,  53, 203, 137, 134, 154, 141, 188, 105, 158,  82, 101,
        154, 127, 170, 137, 159, 130, 143, 168, 137, 155,  90, 117, 118, 174,
         72, 130,  45, 166, 166, 143,  75, 149, 146, 150, 162, 148,  48,  18,
        176, 106, 162,  62, 171, 146, 119, 146, 128, 168, 176, 110, 143, 129,
        137, 129,  62, 147,  56, 195, 130, 178])
tensor(1658) tensor(203)
tensor([ 1, 26,  8, 37, 39,  7,  8, 37, 38,  8, 40,  2,  5, 23, 33, 31,  2, 27,
        12,  8,  1, 26,  8, 37, 30, 26, 18, 26,  8, 18, 33,  7, 22, 26,  8, 26,
        11, 31, 33,  1, 20, 14, 17, 30, 26, 18, 26,  4,  3, 15, 23, 26, 27, 26,
        33, 37, 24, 18, 33, 15, 21, 36, 26,  8,  1, 30,  5, 23, 30, 13, 16,  9,
        16,  5, 37, 27, 40,  8, 40,  8, 11, 38, 23, 26, 37, 13,  8, 33,  9, 23,
         7, 26,  3,  5,  4, 26, 33,  9, 37, 40,  8, 15,  1, 36,  9, 20, 12, 37,
        23, 21, 18, 24,  6, 23,  7, 16,  5, 11, 23,  7,  1,  3, 12, 33,  1, 18,
        31,  6, 39, 26, 17,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
        -1, -1, -1, -1, -1])

# NETWORK

## Basic

This is a basic block for understanding, you can skip this and move to pBLSTM one

In [ ]:
torch.cuda.empty_cache()

class Network(nn.Module):

    def __init__(self):

        super(Network, self).__init__()

        # Adding some sort of embedding layer or feature extractor might help performance.
        # Adding 1D CNN layer
        self.embedding = torch.nn.Sequential(
          nn.Conv1d(in_channels = 28, out_channels = 128, kernel_size = 3, padding=1,stride=1),
          nn.ReLU(),
          nn.BatchNorm1d(128),
        )

        # TODO : look up the documentation. You might need to pass some additional parameters.
        self.lstm = nn.LSTM(input_size = 128, hidden_size = 256, num_layers = 3, bidirectional=True)

        self.classification = nn.Sequential(
            #TODO: Linear layer with in_features from the lstm module above and out_features = OUT_SIZE
            nn.Linear(512, 41)
        )


        self.logSoftmax = nn.LogSoftmax(dim=1)#TODO: Apply a log softmax here. Which dimension would apply it on ?

    def forward(self, x, lx):
        x = x.transpose(1, 2)  # Transpose to (batch_size, input_size, sequence_length) for Conv1d
        x = self.embedding(x)  # Shape: (batch_size, out_channels, new_length)

        x = x.transpose(1, 2)  # Transpose back to (batch_size, sequence_length, out_channels) for LSTM
        x = pack_padded_sequence(x, lx, batch_first=True, enforce_sorted=False)

        # LSTM forward pass
        x, _ = self.lstm(x)

        # Unpack sequence
        x, lx = pad_packed_sequence(x, batch_first=True)

        x = self.classification(x)  # Shape: (batch_size, sequence_length, out_features)
        x = self.logSoftmax(x)       # Shape: (batch_size, sequence_length, out_features)

        return x, lx

## Initialize Basic Network
(If trying out the basic Network)

This network was not used as the final network

In [ ]:
torch.cuda.empty_cache()

model = Network().to(device)
summary(model, x.to(device), lx) # x and lx come from the sanity check above :)

===============================================================================
                           Kernel Shape     Output Shape     Params  \
Layer
0_embedding.Conv1d_0       [28, 128, 3]  [64, 128, 2936]     10.88k
1_embedding.ReLU_1                    -  [64, 128, 2936]          -
2_embedding.BatchNorm1d_2         [128]  [64, 128, 2936]      256.0
3_lstm                                -     [42152, 512]  3.944448M
4_classification.Linear_0     [512, 41]   [64, 2936, 41]    21.033k
5_logSoftmax                          -   [64, 2936, 41]          -

                            Mult-Adds
Layer
0_embedding.Conv1d_0       31.567872M
1_embedding.ReLU_1                  -
2_embedding.BatchNorm1d_2       128.0
3_lstm                       3.93216M
4_classification.Linear_0     20.992k
5_logSoftmax                        -
-------------------------------------------------------------------------------
                          Totals
Total params           3.976617M
Trainable params       3.976617M
Non-trainable params         0.0
Mult-Adds             35.521152M
===============================================================================

,Kernel Shape,Output Shape,Params,Mult-Adds
Layer,,,,
0_embedding.Conv1d_0,"[28, 128, 3]","[64, 128, 2936]",10880.0,31567872.0
1_embedding.ReLU_1,-,"[64, 128, 2936]",NaN,NaN
2_embedding.BatchNorm1d_2,[128],"[64, 128, 2936]",256.0,128.0
3_lstm,-,"[42152, 512]",3944448.0,3932160.0
4_classification.Linear_0,"[512, 41]","[64, 2936, 41]",21033.0,20992.0
5_logSoftmax,-,"[64, 2936, 41]",NaN,NaN

## ASR Network

Below is the final network that was used.

### Pyramid Bi-LSTM (pBLSTM)

In [ ]:
# Utils for network
torch.cuda.empty_cache()

class PermuteBlock(torch.nn.Module):
    def forward(self, x):
        return x.transpose(1, 2)

In [ ]:
class BiLSTM(torch.nn.Module):

    def __init__(self, input_size, hidden_size, num_layers=1):
        super(BiLSTM, self).__init__()

        self.blstm = torch.nn.LSTM(input_size, hidden_size, num_layers, batch_first=True, bidirectional=True)
        self._init_weights()

    def _init_weights(self):
        for name, param in self.blstm.named_parameters():
            if 'weight_ih' in name:
                torch.nn.init.xavier_uniform_(param.data)
            elif 'weight_hh' in name:
                torch.nn.init.orthogonal_(param.data)
            elif 'bias' in name:
                param.data.fill_(0)

    def forward(self, x):
        x, _ = self.blstm(x)
        return x

In [ ]:
import torch
import torch.nn as nn
from torch.autograd import Variable

class LockedDropout(nn.Module):
    def __init__(self, dropout=0.5):
        super().__init__()
        self.dropout = dropout

    def forward(self, x):
        if not self.training:
            return x
        m = x.data.new(1, x.size(1), x.size(2)).bernoulli_(1 - self.dropout)
        mask = Variable(m, requires_grad=False) / (1 - self.dropout)
        mask = mask.expand_as(x)
        return mask * x

In [ ]:
class pBLSTM(torch.nn.Module):
    '''
    Pyramidal BiLSTM
    Read the write up/paper and understand the concepts and then write your implementation here.

    At each step,
    1. Pad your input if it is packed (Unpack it)
    2. Reduce the input length dimension by concatenating feature dimension
        (Tip: Write down the shapes and understand)
        (i) How should  you deal with odd/even length input?
        (ii) How should you deal with input length array (x_lens) after truncating the input?
    3. Pack your input
    4. Pass it into LSTM layer

    To make our implementation modular, we pass 1 layer at a time.
    '''
    def __init__(self, input_size, hidden_size):
        super(pBLSTM, self).__init__()

        self.blstm = torch.nn.LSTM(input_size *2 , hidden_size, num_layers=3, batch_first=True, bidirectional=True, dropout = 0.3)
        self._init_weights()

    def _init_weights(self):
        for name, param in self.blstm.named_parameters():
            if 'weight_ih' in name:
                torch.nn.init.xavier_uniform_(param.data)
            elif 'weight_hh' in name:
                torch.nn.init.orthogonal_(param.data)
            elif 'bias' in name:
                param.data.fill_(0)

    def forward(self, x_packed): # x_packed is a PackedSequence

        # TODO: Pad Packed Sequence
        x, x_lens = pad_packed_sequence(x_packed, batch_first=True)

        # Call self.trunc_reshape() which downsamples the time steps of x and increases the feature dimensions as mentioned above
        # self.trunc_reshape will return 2 outputs. What are they? Think about what quantites are changing.
        x, x_lens = self.trunc_reshape(x, x_lens)
        # TODO: Pack Padded Sequence. What output(s) would you get?
        x_packed = pack_padded_sequence(x, x_lens, batch_first=True, enforce_sorted=False)
        # TODO: Pass the sequence through bLSTM
        x, _ = self.blstm(x_packed)
        # What do you return?
        return x

    def trunc_reshape(self, x, x_lens):
        # TODO: If you have odd number of timesteps, how can you handle it? (Hint: You can exclude them)
        batch_size, seq_len, feat_dim = x.size()
        if seq_len % 2 == 1:
            x = x[:, :-1, :]
            x_lens = x_lens - 1
        # TODO: Reshape x. When reshaping x, you have to reduce number of timesteps by a downsampling factor while increasing number of features by the same factor
        x = x.reshape(batch_size, seq_len // 2, feat_dim * 2)
        # TODO: Reduce lengths by the same downsampling factor
        x_lens = x_lens // 2

        return x, x_lens

In [ ]:
class pBLSTMWithDropout(torch.nn.Module):
    '''
    Pyramidal BiLSTM
    Read the write up/paper and understand the concepts and then write your implementation here.

    At each step,
    1. Pad your input if it is packed (Unpack it)
    2. Reduce the input length dimension by concatenating feature dimension
        (Tip: Write down the shapes and understand)
        (i) How should  you deal with odd/even length input?
        (ii) How should you deal with input length array (x_lens) after truncating the input?
    3. Pack your input
    4. Pass it into LSTM layer

    To make our implementation modular, we pass 1 layer at a time.
    '''
    def __init__(self, input_size, hidden_size):
        super(pBLSTM, self).__init__()

        self.blstm = torch.nn.LSTM(input_size *2 , hidden_size, num_layers=3, batch_first=True, bidirectional=True, dropout = 0.3)
        self.locked_dropout = LockedDropout(0.3)
        self._init_weights()

    def _init_weights(self):
        for name, param in self.blstm.named_parameters():
            if 'weight_ih' in name:
                torch.nn.init.xavier_uniform_(param.data)
            elif 'weight_hh' in name:
                torch.nn.init.orthogonal_(param.data)
            elif 'bias' in name:
                param.data.fill_(0)

    def forward(self, x_packed,x_lens): # x_packed is a PackedSequence

        # TODO: Pad Packed Sequence
        x, x_lens = pad_packed_sequence(x_packed, batch_first=True)

        # Call self.trunc_reshape() which downsamples the time steps of x and increases the feature dimensions as mentioned above
        # self.trunc_reshape will return 2 outputs. What are they? Think about what quantites are changing.
        x, x_lens = self.trunc_reshape(x, x_lens)
        # TODO: Pack Padded Sequence. What output(s) would you get?
        x_packed = pack_padded_sequence(x, x_lens, batch_first=True, enforce_sorted=False)
        # TODO: Pass the sequence through bLSTM
        x, _ = self.blstm(x_packed)
        # What do you return?
        return x

    def trunc_reshape(self, x, x_lens):
        # TODO: If you have odd number of timesteps, how can you handle it? (Hint: You can exclude them)
        batch_size, seq_len, feat_dim = x.size()
        if seq_len % 2 == 1:
            x = x[:, :-1, :]
            x_lens = x_lens - 1
        # TODO: Reshape x. When reshaping x, you have to reduce number of timesteps by a downsampling factor while increasing number of features by the same factor
        x = x.reshape(batch_size, seq_len // 2, feat_dim * 2)
        # TODO: Reduce lengths by the same downsampling factor
        x_lens = x_lens // 2

        return x, x_lens

### Encoder

In [ ]:
# class pBLSTMWithDropout(torch.nn.Module):
#     def __init__(self, input_size, hidden_size, dropout=0.3):
#         super(pBLSTMWithDropout, self).__init__()
#         self.pBLSTM = torch.nn.LSTM(input_size, hidden_size, num_layers=1, bidirectional=True, batch_first=True)
#         self.dropout = LockedDropout(dropout=dropout)

#     def forward(self, x, x_lens):

#         # Pass through pBLSTM
#         packed_output, _ = self.pBLSTM(x)

#         # Unpack to apply dropout
#         output, _ = pad_packed_sequence(packed_output, batch_first=True)
#         output = self.dropout(output)

#         # Repack the output
#         packed_output = pack_padded_sequence(output, x_lens, batch_first=True, enforce_sorted=False)
#         return packed_output

In [ ]:
class Encoder(torch.nn.Module):
    '''
    The Encoder takes utterances as inputs and returns latent feature representations
    '''
    def __init__(self, input_size, encoder_hidden_size, num_pblstm_layers=3):
        super(Encoder, self).__init__()


        self.embedding = torch.nn.Sequential(
            nn.Conv1d(in_channels=input_size, out_channels=64, kernel_size=3, stride=1, padding=1),
            torch.nn.BatchNorm1d(64),
            torch.nn.GELU(),
            torch.nn.Conv1d(in_channels=64, out_channels=128, kernel_size=3, padding=1, stride=1),
            torch.nn.BatchNorm1d(128),
            torch.nn.GELU(),
            torch.nn.Conv1d(in_channels=128, out_channels=256, kernel_size=3, padding=1, stride=1),
            torch.nn.BatchNorm1d(256),
            torch.nn.GELU()
            # nn.Conv1d(in_channels=encoder_hidden_size//2, out_channels=encoder_hidden_size, kernel_size=3, stride=1, padding=1),
            # nn.ReLU(),
            # nn.BatchNorm1d(encoder_hidden_size),
        )
        # 256
        self._init_conv_weights()
        self.bLSTM = BiLSTM(encoder_hidden_size, encoder_hidden_size, num_layers=1)
        # pBLSTMs_list = [pBLSTM(encoder_hidden_size * (2**i) * 2, encoder_hidden_size * (2**i) * 2) for i in range(num_pblstm_layers)]

        self.pBLSTMs = torch.nn.Sequential( # How many pBLSTMs are required?
            # TODO: Fill this up with pBLSTMs - What should the input_size be?
            # Hint: You are downsampling timesteps by a factor of 2, upsampling features by a factor of 2 and the LSTM is bidirectional)

            # Optional: Dropout/Locked Dropout after each pBLSTM (Not needed for early submission)
            # https://github.com/salesforce/awd-lstm-lm/blob/dfd3cb0235d2caf2847a4d53e1cbd495b781b5d2/locked_dropout.py#L5
            # ...
            # ...
            # * pBLSTMs_list
            pBLSTM(encoder_hidden_size * 2, encoder_hidden_size),
            pBLSTM(encoder_hidden_size * 2, encoder_hidden_size),


        )
        self.locked_dropout = LockedDropout(0.3)

    def _init_conv_weights(self):
        for m in self.embedding.modules():
            if isinstance(m, nn.Conv1d):
                torch.nn.init.kaiming_normal_(m.weight, mode='fan_out', nonlinearity='relu')
                if m.bias is not None:
                    torch.nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm1d):
                torch.nn.init.constant_(m.weight, 1)
                torch.nn.init.constant_(m.bias, 0)

    def forward(self, x, x_lens):
        # Where are x and x_lens coming from? The dataloader
        #TODO: Call the embedding layer
        x = PermuteBlock()(x)
        x = self.embedding(x)
        x = PermuteBlock()(x)
        # TODO: Pack Padded Sequence
        x_packed = pack_padded_sequence(x, x_lens, batch_first=True, enforce_sorted=False)
        # TODO: Pass Sequence through the pyramidal Bi-LSTM layer
        x = self.bLSTM(x_packed)
        for pBLSTM in self.pBLSTMs:
            x = pBLSTM(x)
            x, x_lens = pad_packed_sequence(x, batch_first=True)
            x = self.locked_dropout(x)
            x = pack_padded_sequence(x, x_lens, batch_first=True, enforce_sorted=False)
        # TODO: Pad Packed Sequence
        encoder_outputs, encoder_lens = pad_packed_sequence(x, batch_first=True)



        # Remember the number of output(s) each function returns

        return encoder_outputs, encoder_lens

### Decoder

In [ ]:
class Decoder(torch.nn.Module):

    def __init__(self, embed_size, output_size= 41, dropout=0.3):
        super().__init__()

        self.mlp = torch.nn.Sequential(
            PermuteBlock(), torch.nn.BatchNorm1d(embed_size), PermuteBlock(),
            #TODO define your MLP arch. Refer HW1P2
            #Use Permute Block before and after BatchNorm1d() to match the size
            torch.nn.Linear(embed_size, embed_size * 2),
            torch.nn.GELU(),
            torch.nn.Dropout(dropout),
            PermuteBlock(), torch.nn.BatchNorm1d(embed_size * 2), PermuteBlock(),
            torch.nn.Linear(embed_size * 2, embed_size // 2),
            torch.nn.GELU(),
            torch.nn.Dropout(dropout),
            PermuteBlock(), torch.nn.BatchNorm1d(embed_size // 2), PermuteBlock(),
            torch.nn.Linear(embed_size // 2, embed_size // 4),
            torch.nn.GELU(),
            torch.nn.Dropout(dropout),
            PermuteBlock(), torch.nn.BatchNorm1d(embed_size // 4), PermuteBlock(),
            # torch.nn.Linear(embed_size // 4, embed_size // 8),
            # torch.nn.ReLU(),
            # PermuteBlock(), torch.nn.BatchNorm1d(embed_size // 8), PermuteBlock(),
            torch.nn.Linear(embed_size // 4, output_size)
        )

        self.softmax = torch.nn.LogSoftmax(dim=2)
        self._init_weights()

    def _init_weights(self):
        for m in self.mlp.modules():
            if isinstance(m, nn.Linear):
                torch.nn.init.xavier_uniform_(m.weight)
                if m.bias is not None:
                    torch.nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm1d):
                torch.nn.init.constant_(m.weight, 1)
                torch.nn.init.constant_(m.bias, 0)

    def forward(self, encoder_out):
        #TODO call your MLP
        #TODO Think what should be the final output of the decoder for the classification
        out = self.softmax(self.mlp(encoder_out))
        return out

In [ ]:
class ASRModel(torch.nn.Module):

    def __init__(self, input_size, embed_size= 256, output_size= len(PHONEMES)):
        super().__init__()

        self.augmentations  = torch.nn.Sequential(
            #TODO Add Time Masking/ Frequency Masking
            #Hint: See how to use PermuteBlock() function defined above
        )
        self.encoder        = Encoder(input_size, embed_size, num_pblstm_layers=3)
        self.decoder        = Decoder(512, output_size,dropout=0.3)



    def forward(self, x, lengths_x):

        if self.training:
            x = self.augmentations(x)

        encoder_out, encoder_lens   = self.encoder(x, lengths_x)
        decoder_out                 = self.decoder(encoder_out)

        return decoder_out, encoder_lens

## Initialize ASR Network

In [ ]:
model = ASRModel(
    input_size  = 28,
    embed_size  = 256,
    output_size = len(PHONEMES)
).to(device)
print(model)
summary(model, x.to(device), lx)

ASRModel(
  (augmentations): Sequential()
  (encoder): Encoder(
    (embedding): Sequential(
      (0): Conv1d(28, 64, kernel_size=(3,), stride=(1,), padding=(1,))
      (1): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): GELU(approximate='none')
      (3): Conv1d(64, 128, kernel_size=(3,), stride=(1,), padding=(1,))
      (4): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (5): GELU(approximate='none')
      (6): Conv1d(128, 256, kernel_size=(3,), stride=(1,), padding=(1,))
      (7): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (8): GELU(approximate='none')
    )
    (bLSTM): BiLSTM(
      (blstm): LSTM(256, 256, batch_first=True, bidirectional=True)
    )
    (pBLSTMs): Sequential(
      (0): pBLSTM(
        (blstm): LSTM(1024, 256, num_layers=3, batch_first=True, dropout=0.3, bidirectional=True)
      )
      (1): pBLSTM(
        (blstm): LSTM(1024, 256, num_layers=3, batch_first=True, dropout=0.3, bidirectional=True)
      )
    )
    (locked_dropout): LockedDropout()
  )
  (decoder): Decoder(
    (mlp): Sequential(
      (0): PermuteBlock()
      (1): BatchNorm1d(512, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (2): PermuteBlock()
      (3): Linear(in_features=512, out_features=1024, bias=True)
      (4): GELU(approximate='none')
      (5): Dropout(p=0.3, inplace=False)
      (6): PermuteBlock()
      (7): BatchNorm1d(1024, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (8): PermuteBlock()
      (9): Linear(in_features=1024, out_features=256, bias=True)
      (10): GELU(approximate='none')
      (11): Dropout(p=0.3, inplace=False)
      (12): PermuteBlock()
      (13): BatchNorm1d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (14): PermuteBlock()
      (15): Linear(in_features=256, out_features=128, bias=True)
      (16): GELU(approximate='none')
      (17): Dropout(p=0.3, inplace=False)
      (18): PermuteBlock()
      (19): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (20): PermuteBlock()
      (21): Linear(in_features=128, out_features=41, bias=True)
    )
    (softmax): LogSoftmax(dim=2)
  )
)
===============================================================================================
                                          Kernel Shape     Output Shape  \
Layer
0_augmentations                                      -   [64, 1658, 28]
1_encoder.embedding.Conv1d_0               [28, 64, 3]   [64, 64, 1658]
2_encoder.embedding.BatchNorm1d_1                 [64]   [64, 64, 1658]
3_encoder.embedding.GELU_2                           -   [64, 64, 1658]
4_encoder.embedding.Conv1d_3              [64, 128, 3]  [64, 128, 1658]
5_encoder.embedding.BatchNorm1d_4                [128]  [64, 128, 1658]
6_encoder.embedding.GELU_5                           -  [64, 128, 1658]
7_encoder.embedding.Conv1d_6             [128, 256, 3]  [64, 256, 1658]
8_encoder.embedding.BatchNorm1d_7                [256]  [64, 256, 1658]
9_encoder.embedding.GELU_8                           -  [64, 256, 1658]
10_encoder.bLSTM.LSTM_blstm                          -     [82772, 512]
11_encoder.pBLSTMs.0.LSTM_blstm                      -     [41372, 512]
12_encoder.LockedDropout_locked_dropout              -   [64, 829, 512]
13_encoder.pBLSTMs.1.LSTM_blstm                      -     [20638, 512]
14_encoder.LockedDropout_locked_dropout              -   [64, 414, 512]
15_decoder.mlp.PermuteBlock_0                        -   [64, 512, 414]
16_decoder.mlp.BatchNorm1d_1                     [512]   [64, 512, 414]
17_decoder.mlp.PermuteBlock_2                        -   [64, 414, 512]
18_decoder.mlp.Linear_3                    [512, 1024]  [64, 414, 1024]
19_decoder.mlp.GELU_4                                -  [64, 414, 1024]
20_decoder.mlp.Dropout_5                             -  [64, 414, 1024]
21_decoder.mlp.PermuteBlock_6                        -  [64, 1024, 414]
22_decoder.mlp.BatchNorm1d_7                    [1024]  [64, 1024, 414]
23_decoder.mlp.PermuteBlock_8                        -  [64, 414, 1024]
24_decoder.mlp.Linear_9                    [1024, 256]   [64, 414, 256]
25_decoder.mlp.GELU_10                               -   [64, 414, 256]
26_decoder.mlp.Dropout_11                            -   [64, 414, 256]
27_decoder.mlp.PermuteBlock_12                       -   [64, 256, 414]
28_decoder.mlp.BatchNorm1d_13                    [256]   [64, 256, 414]
29_decoder.mlp.PermuteBlock_14                       -   [64, 414, 256]
30_decoder.mlp.Linear_15                    [256, 128]   [64, 414, 128]
31_decoder.mlp.GELU_16                               -   [64, 414, 128]
32_decoder.mlp.Dropout_17                            -   [64, 414, 128]
33_decoder.mlp.PermuteBlock_18                       -   [64, 128, 414]
34_decoder.mlp.BatchNorm1d_19                    [128]   [64, 128, 414]
35_decoder.mlp.PermuteBlock_20                       -   [64, 414, 128]
36_decoder.mlp.Linear_21                     [128, 41]    [64, 414, 41]
37_decoder.LogSoftmax_softmax                        -    [64, 414, 41]

                                            Params    Mult-Adds
Layer
0_augmentations                                  -            -
1_encoder.embedding.Conv1d_0                 5.44k    8.913408M
2_encoder.embedding.BatchNorm1d_1            128.0         64.0
3_encoder.embedding.GELU_2                       -            -
4_encoder.embedding.Conv1d_3               24.704k   40.747008M
5_encoder.embedding.BatchNorm1d_4            256.0        128.0
6_encoder.embedding.GELU_5                       -            -
7_encoder.embedding.Conv1d_6                98.56k  162.988032M
8_encoder.embedding.BatchNorm1d_7            512.0        256.0
9_encoder.embedding.GELU_8                       -            -
10_encoder.bLSTM.LSTM_blstm              1.052672M    1.048576M
11_encoder.pBLSTMs.0.LSTM_blstm          5.779456M    5.767168M
12_encoder.LockedDropout_locked_dropout          -            -
13_encoder.pBLSTMs.1.LSTM_blstm          5.779456M    5.767168M
14_encoder.LockedDropout_locked_dropout          -            -
15_decoder.mlp.PermuteBlock_0                    -            -
16_decoder.mlp.BatchNorm1d_1                1.024k        512.0
17_decoder.mlp.PermuteBlock_2                    -            -
18_decoder.mlp.Linear_3                   525.312k     524.288k
19_decoder.mlp.GELU_4                            -            -
20_decoder.mlp.Dropout_5                         -            -
21_decoder.mlp.PermuteBlock_6                    -            -
22_decoder.mlp.BatchNorm1d_7                2.048k       1.024k
23_decoder.mlp.PermuteBlock_8                    -            -
24_decoder.mlp.Linear_9                     262.4k     262.144k
25_decoder.mlp.GELU_10                           -            -
26_decoder.mlp.Dropout_11                        -            -
27_decoder.mlp.PermuteBlock_12                   -            -
28_decoder.mlp.BatchNorm1d_13                512.0        256.0
29_decoder.mlp.PermuteBlock_14                   -            -
30_decoder.mlp.Linear_15                   32.896k      32.768k
31_decoder.mlp.GELU_16                           -            -
32_decoder.mlp.Dropout_17                        -            -
33_decoder.mlp.PermuteBlock_18                   -            -
34_decoder.mlp.BatchNorm1d_19                256.0        128.0
35_decoder.mlp.PermuteBlock_20                   -            -
36_decoder.mlp.Linear_21                    5.289k       5.248k
37_decoder.LogSoftmax_softmax                    -            -
-----------------------------------------------------------------------------------------------
                           Totals
Total params           13.570921M
Trainable params       13.570921M
Non-trainable params          0.0
Mult-Adds             226.058176M
===============================================================================================

,Kernel Shape,Output Shape,Params,Mult-Adds
Layer,,,,
0_augmentations,-,"[64, 1658, 28]",NaN,NaN
1_encoder.embedding.Conv1d_0,"[28, 64, 3]","[64, 64, 1658]",5440.0,8913408.0
2_encoder.embedding.BatchNorm1d_1,[64],"[64, 64, 1658]",128.0,64.0
3_encoder.embedding.GELU_2,-,"[64, 64, 1658]",NaN,NaN
4_encoder.embedding.Conv1d_3,"[64, 128, 3]","[64, 128, 1658]",24704.0,40747008.0
5_encoder.embedding.BatchNorm1d_4,[128],"[64, 128, 1658]",256.0,128.0
6_encoder.embedding.GELU_5,-,"[64, 128, 1658]",NaN,NaN
7_encoder.embedding.Conv1d_6,"[128, 256, 3]","[64, 256, 1658]",98560.0,162988032.0
8_encoder.embedding.BatchNorm1d_7,[256],"[64, 256, 1658]",512.0,256.0
9_encoder.embedding.GELU_8,-,"[64, 256, 1658]",NaN,NaN
10_encoder.bLSTM.LSTM_blstm,-,"[82772, 512]",1052672.0,1048576.0
11_encoder.pBLSTMs.0.LSTM_blstm,-,"[41372, 512]",5779456.0,5767168.0
12_encoder.LockedDropout_locked_dropout,-,"[64, 829, 512]",NaN,NaN
13_encoder.pBLSTMs.1.LSTM_blstm,-,"[20638, 512]",5779456.0,5767168.0
14_encoder.LockedDropout_locked_dropout,-,"[64, 414, 512]",NaN,NaN
15_decoder.mlp.PermuteBlock_0,-,"[64, 512, 414]",NaN,NaN
16_decoder.mlp.BatchNorm1d_1,[512],"[64, 512, 414]",1024.0,512.0
17_decoder.mlp.PermuteBlock_2,-,"[64, 414, 512]",NaN,NaN
18_decoder.mlp.Linear_3,"[512, 1024]","[64, 414, 1024]",525312.0,524288.0
19_decoder.mlp.GELU_4,-,"[64, 414, 1024]",NaN,NaN
20_decoder.mlp.Dropout_5,-,"[64, 414, 1024]",NaN,NaN
21_decoder.mlp.PermuteBlock_6,-,"[64, 1024, 414]",NaN,NaN
22_decoder.mlp.BatchNorm1d_7,[1024],"[64, 1024, 414]",2048.0,1024.0
23_decoder.mlp.PermuteBlock_8,-,"[64, 414, 1024]",NaN,NaN
24_decoder.mlp.Linear_9,"[1024, 256]","[64, 414, 256]",262400.0,262144.0
25_decoder.mlp.GELU_10,-,"[64, 414, 256]",NaN,NaN
26_decoder.mlp.Dropout_11,-,"[64, 414, 256]",NaN,NaN
27_decoder.mlp.PermuteBlock_12,-,"[64, 256, 414]",NaN,NaN
28_decoder.mlp.BatchNorm1d_13,[256],"[64, 256, 414]",512.0,256.0
29_decoder.mlp.PermuteBlock_14,-,"[64, 414, 256]",NaN,NaN
30_decoder.mlp.Linear_15,"[256, 128]","[64, 414, 128]",32896.0,32768.0
31_decoder.mlp.GELU_16,-,"[64, 414, 128]",NaN,NaN
32_decoder.mlp.Dropout_17,-,"[64, 414, 128]",NaN,NaN
33_decoder.mlp.PermuteBlock_18,-,"[64, 128, 414]",NaN,NaN
34_decoder.mlp.BatchNorm1d_19,[128],"[64, 128, 414]",256.0,128.0
35_decoder.mlp.PermuteBlock_20,-,"[64, 414, 128]",NaN,NaN
36_decoder.mlp.Linear_21,"[128, 41]","[64, 414, 41]",5289.0,5248.0
37_decoder.LogSoftmax_softmax,-,"[64, 414, 41]",NaN,NaN

# Training Config
Initialize Loss Criterion, Optimizer, CTC Beam Decoder, Scheduler, Scaler (Mixed-Precision), etc.

In [ ]:
#TODO


# Define CTC loss as the criterion. How would the losses be reduced?
# CTC Loss: https://pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html
# Refer to the handout for hints
criterion = torch.nn.CTCLoss(blank=0, zero_infinity=True)

optimizer =  torch.optim.AdamW(model.parameters(), lr=config['lr'])

# Declare the decoder. Use the CTC Beam Decoder to decode phonemes
# CTC Beam Decoder Doc: https://github.com/parlance/ctcdecode
decoder = CTCBeamDecoder(labels=LABELS, model_path=None, beam_width=config['beam_width'], log_probs_input=True)

# scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config['epochs'], eta_min=0)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, threshold=0.02, verbose=True)

# Mixed Precision, if you need it
scaler = torch.cuda.amp.GradScaler()

# Decode Prediction

In [ ]:
def decode_prediction(output, output_lens, decoder, PHONEME_MAP= LABELS):

    # TODO: look at docs for CTC.decoder and find out what is returned here. Check the shape of output and expected shape in decode.
    beam_results, beam_scores, timesteps, out_lens = decoder.decode(output, seq_lens= output_lens) #lengths - list of lengths

    pred_strings                    = []

    for i in range(output_lens.shape[0]):
        #TODO: Create the prediction from the output of decoder.decode. Don't forget to map it using PHONEMES_MAP.
        # Get the sequence for this sample
        sequence = beam_results[i][0][:out_lens[i][0]] # Get first beam result up to its length

        # Map indices to phoneme labels
        pred_str = ' '.join([PHONEME_MAP[idx.item()] for idx in sequence])
        pred_strings.append(pred_str)

    return pred_strings

def calculate_levenshtein(output, label, output_lens, label_lens, decoder, PHONEME_MAP= LABELS): # y - sequence of integers

    dist            = 0
    batch_size      = label.shape[0]

    print(output.shape, label.shape)
    print(output_lens, label_lens)
    print((output_lens.shape[0]))
    pred_strings    = decode_prediction(output, output_lens, decoder, PHONEME_MAP)

    for i in range(batch_size):
        # TODO: Get predicted string and label string for each element in the batch
        pred_string = pred_strings[i]
        label_indices = label[i][:label_lens[i]]
        label_string = ' '.join([PHONEME_MAP[idx.item()] for idx in label_indices])
        dist += Levenshtein.distance(pred_string, label_string)

    dist /= batch_size # TODO: Uncomment this, but think about why we are doing this
    return dist

In [ ]:
def decode_prediction(output, output_lens, decoder, PHONEME_MAP=LABELS):
    # If shape is [T, B, C], transpose to [B, T, C]
    # if output.shape[1] == output_lens.shape[0]:  # Check if second dimension matches batch size

    ############## Use torch.permute instead of transpose #####################
    output = torch.permute(output, (1, 0, 2))

    beam_results, beam_scores, timesteps, out_lens = decoder.decode(output, seq_lens=output_lens)

    pred_strings = []
    batch_size = output.size(0)
    for i in range(batch_size):
        pred = beam_results[i][0][:out_lens[i][0]].numpy()
        # if i == 0:
        #     print(pred)
        pred_string = ''.join([PHONEME_MAP[idx] for idx in pred])
        # if i == 0:
        #     print(pred_string)
        pred_strings.append(pred_string)
    return pred_strings

# Calculate Levenshtein Distance Function
def calculate_levenshtein(output, label, output_lens, label_lens, decoder, PHONEME_MAP=LABELS):
    dist = 0
    batch_size = label.shape[0]

    # Ensure output is in the correct shape before passing to decode_prediction
    # if output.size(0) < output.size(1):  # If shape is [T, B, C]
    # output = output.transpose(0, 1)   # Change to [B, T, C]

    pred_strings = decode_prediction(output, output_lens, decoder, PHONEME_MAP)
    # print(batch_size)
    # print(len(pred_strings))
    # print(label.shape)
    # print(label_lens.shape)
    # print(output.shape)
    # print(output_lens.shape)
    for i in range(batch_size):
        pred_string = pred_strings[i]
        label_seq = label[i][:label_lens[i]].cpu().numpy()
        label_string = ''.join([PHONEME_MAP[idx] for idx in label_seq])
        dist += Levenshtein.distance(pred_string, label_string)

    dist /= batch_size  # Average over batch size
    return dist

# Test Implementation

In [ ]:
# test code to check shapes

model.eval()
for i, data in enumerate(val_loader, 0):
    x, y, lx, ly = data
    x, y = x.to(device), y.to(device)
    h, lh = model(x, lx)
    print(h.shape)
    h = torch.permute(h, (1, 0, 2))
    print(h.shape, y.shape)
    loss = criterion(h, y, lh, ly)
    print(loss)

    print(calculate_levenshtein(h, y, lx, ly, decoder, LABELS))

    break

torch.Size([64, 734, 41])
torch.Size([734, 64, 41]) torch.Size([64, 265])
tensor(7.6849, device='cuda:0', grad_fn=<MeanBackward0>)
208.765625

# WandB

You will need to fetch your api key from wandb.ai

In [ ]:
import wandb
wandb.login(key="0cc2199d5dbab5108d50abc33d06f093f13e6a18")

wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: Currently logged in as: pkotchav (pkotchav-carnegie-mellon-university). Use `wandb login --relogin` to force relogin
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc

True

In [ ]:
run = wandb.init(
    name = "final-submission-r4", ## Wandb creates random run names if you skip this field
    reinit = True, ### Allows reinitalizing runs when you re-run this cell
    # run_id = ### Insert specific run id here if you want to resume a previous run
    # resume = "must" ### You need this to resume previous runs, but comment out reinit = True when using this
    project = "hw3p2-ablations", ### Project should be created in your wandb account
    config = config ### Wandb Config for your run
)

# Train Functions

In [ ]:
from tqdm import tqdm

def train_model(model, train_loader, criterion, optimizer):

    model.train()
    batch_bar = tqdm(total=len(train_loader), dynamic_ncols=True, leave=False, position=0, desc='Train')

    total_loss = 0

    for i, data in enumerate(train_loader):
        optimizer.zero_grad()

        x, y, lx, ly = data
        x, y = x.to(device), y.to(device)

        with torch.cuda.amp.autocast():
            h, lh = model(x, lx)
            h = torch.permute(h, (1, 0, 2))
            # if i == 0:
                # print(h.shape)
            #     print(lh.shape)
            #     print(y.shape)
            #     print(ly.shape)
                # print(h)
            #     print(lh)
            #     print(y)
            #     print(ly)
            loss = criterion(h, y, lh, ly)

        total_loss += loss.item()

        batch_bar.set_postfix(
            loss="{:.04f}".format(float(total_loss / (i + 1))),
            lr="{:.06f}".format(float(optimizer.param_groups[0]['lr'])))

        batch_bar.update() # Update tqdm bar

        # Another couple things you need for FP16.
        scaler.scale(loss).backward() # This is a replacement for loss.backward()
        scaler.step(optimizer) # This is a replacement for optimizer.step()
        scaler.update() # This is something added just for FP16
        # loss.backward()
        # optimizer.step()

        del x, y, lx, ly, h, lh, loss
        torch.cuda.empty_cache()

    batch_bar.close() # You need this to close the tqdm bar

    return total_loss / len(train_loader)


def validate_model(model, val_loader, decoder, phoneme_map= LABELS):

    model.eval()
    batch_bar = tqdm(total=len(val_loader), dynamic_ncols=True, position=0, leave=False, desc='Val')

    total_loss = 0
    vdist = 0

    for i, data in enumerate(val_loader):

        x, y, lx, ly = data
        x, y = x.to(device), y.to(device)

        with torch.inference_mode():
            h, lh = model(x, lx)
            h = torch.permute(h, (1, 0, 2))
            loss = criterion(h, y, lh, ly)

        total_loss += float(loss)
        vdist += calculate_levenshtein(h, y, lh, ly, decoder, phoneme_map)

        batch_bar.set_postfix(loss="{:.04f}".format(float(total_loss / (i + 1))), dist="{:.04f}".format(float(vdist / (i + 1))))

        batch_bar.update()

        del x, y, lx, ly, h, lh, loss
        torch.cuda.empty_cache()

    batch_bar.close()
    total_loss = total_loss/len(val_loader)
    val_dist = vdist/len(val_loader)
    return total_loss, val_dist

## Training Setup

In [ ]:
def save_model(model, optimizer, scheduler, metric, epoch, path):
    torch.save(
        {'model_state_dict'         : model.state_dict(),
         'optimizer_state_dict'     : optimizer.state_dict(),
         'scheduler_state_dict'     : scheduler.state_dict(),
         metric[0]                  : metric[1],
         'epoch'                    : epoch},
         path
    )

def load_model(path, model, metric= 'valid_acc', optimizer= None, scheduler= None):

    checkpoint = torch.load(path)
    model.load_state_dict(checkpoint['model_state_dict'])

    if optimizer != None:
        optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    if scheduler != None:
        scheduler.load_state_dict(checkpoint['scheduler_state_dict'])

    epoch   = checkpoint['epoch']
    metric  = checkpoint[metric]

    return [model, optimizer, scheduler, epoch, metric]

In [ ]:
# This is for checkpointing, if you're doing it over multiple sessions

last_epoch_completed = 0
start = last_epoch_completed
end = config["epochs"]
best_lev_dist = float("inf") # if you're restarting from some checkpoint, use what you saw there.
epoch_model_path = '/content/hw3p2/finalbig/last.pth'#TODO set the model path( Optional, you can just store best one. Make sure to make the changes below )
best_model_path = '/content/hw3p2/finalbig/best.pth'#TODO set best model path

In [ ]:
torch.cuda.empty_cache()
gc.collect()

#TODO: Please complete the training loop

for epoch in range(0, config['epochs']):

    print("\nEpoch: {}/{}".format(epoch+1, config['epochs']))

    curr_lr = optimizer.param_groups[0]['lr'] #TODO

    train_loss              = train_model(model, train_loader, criterion, optimizer) #TODO
    valid_loss, valid_dist  = validate_model(model, val_loader, decoder, phoneme_map=LABELS) #TODO
    scheduler.step(valid_dist)

    print("\tTrain Loss {:.04f}\t Learning Rate {:.07f}".format(train_loss, curr_lr))
    print("\tVal Dist {:.04f}%\t Val Loss {:.04f}".format(valid_dist, valid_loss))


    wandb.log({
        'train_loss': train_loss,
        'valid_dist': valid_dist,
        'valid_loss': valid_loss,
        'lr'        : curr_lr
    })

    save_model(model, optimizer, scheduler, ['valid_dist', valid_dist], epoch, epoch_model_path)
    wandb.save(epoch_model_path)
    print("Saved epoch model")

    if valid_dist <= best_lev_dist:
        best_lev_dist = valid_dist
        save_model(model, optimizer, scheduler, ['valid_dist', valid_dist], epoch, best_model_path)
        wandb.save(best_model_path)
        print("Saved best model")
      # You may find it interesting to exlplore Wandb Artifcats to version your models
run.finish()

Epoch: 1/60

	Train Loss 3.4328	 Learning Rate 0.0020000
	Val Dist 66.6528%	 Val Loss 3.2015

wandb: WARNING Saving files without folders. If you want to preserve subdirectories pass base_path to wandb.save, i.e. wandb.save("/mnt/folder/file.h5", base_path="/mnt")

Saved epoch model
Saved best model

Epoch: 2/60

	Train Loss 2.0620	 Learning Rate 0.0020000
	Val Dist 23.1374%	 Val Loss 1.0749
Saved epoch model
Saved best model

Epoch: 3/60

	Train Loss 1.1238	 Learning Rate 0.0020000
	Val Dist 15.6210%	 Val Loss 0.7361
Saved epoch model
Saved best model

Epoch: 4/60

	Train Loss 0.8691	 Learning Rate 0.0020000
	Val Dist 12.4566%	 Val Loss 0.5921
Saved epoch model
Saved best model

Epoch: 5/60

	Train Loss 0.7363	 Learning Rate 0.0020000
	Val Dist 10.8852%	 Val Loss 0.5185
Saved epoch model
Saved best model

Epoch: 6/60

	Train Loss 0.6528	 Learning Rate 0.0020000
	Val Dist 9.8750%	 Val Loss 0.4746
Saved epoch model
Saved best model

Epoch: 7/60

	Train Loss 0.5923	 Learning Rate 0.0020000
	Val Dist 9.4314%	 Val Loss 0.4576
Saved epoch model
Saved best model

Epoch: 8/60

	Train Loss 0.5463	 Learning Rate 0.0020000
	Val Dist 8.8742%	 Val Loss 0.4331
Saved epoch model
Saved best model

Epoch: 9/60

	Train Loss 0.5073	 Learning Rate 0.0020000
	Val Dist 8.0399%	 Val Loss 0.3885
Saved epoch model
Saved best model

Epoch: 10/60

	Train Loss 0.4794	 Learning Rate 0.0020000
	Val Dist 8.6585%	 Val Loss 0.4216
Saved epoch model

Epoch: 11/60

	Train Loss 0.4569	 Learning Rate 0.0020000
	Val Dist 7.4060%	 Val Loss 0.3567
Saved epoch model
Saved best model

Epoch: 12/60

	Train Loss 0.4278	 Learning Rate 0.0020000
	Val Dist 7.1481%	 Val Loss 0.3610
Saved epoch model
Saved best model

Epoch: 13/60

	Train Loss 0.4104	 Learning Rate 0.0020000
	Val Dist 6.7929%	 Val Loss 0.3359
Saved epoch model
Saved best model

Epoch: 14/60

	Train Loss 0.3853	 Learning Rate 0.0020000
	Val Dist 6.4747%	 Val Loss 0.3182
Saved epoch model
Saved best model

Epoch: 15/60

	Train Loss 0.3729	 Learning Rate 0.0020000
	Val Dist 6.5544%	 Val Loss 0.3257
Saved epoch model

Epoch: 16/60

	Train Loss 0.3553	 Learning Rate 0.0020000
	Val Dist 6.2552%	 Val Loss 0.3141
Saved epoch model
Saved best model

Epoch: 17/60

	Train Loss 0.3515	 Learning Rate 0.0020000
	Val Dist 6.3208%	 Val Loss 0.3226
Saved epoch model

Epoch: 18/60

	Train Loss 0.3401	 Learning Rate 0.0020000
	Val Dist 6.0107%	 Val Loss 0.3004
Saved epoch model
Saved best model

Epoch: 19/60

	Train Loss 0.3221	 Learning Rate 0.0020000
	Val Dist 5.9697%	 Val Loss 0.3010
Saved epoch model
Saved best model

Epoch: 20/60

	Train Loss 0.3179	 Learning Rate 0.0020000
	Val Dist 5.7710%	 Val Loss 0.2977
Saved epoch model
Saved best model

Epoch: 21/60

	Train Loss 0.3063	 Learning Rate 0.0020000
	Val Dist 5.6893%	 Val Loss 0.2949
Saved epoch model
Saved best model

Epoch: 22/60

	Train Loss 0.3027	 Learning Rate 0.0020000
	Val Dist 5.7054%	 Val Loss 0.2936
Saved epoch model

Epoch: 23/60

	Train Loss 0.2976	 Learning Rate 0.0020000
	Val Dist 5.6643%	 Val Loss 0.2886
Saved epoch model
Saved best model

Epoch: 24/60

	Train Loss 0.2862	 Learning Rate 0.0020000
	Val Dist 5.4413%	 Val Loss 0.2833
Saved epoch model
Saved best model

Epoch: 25/60

	Train Loss 0.2766	 Learning Rate 0.0020000
	Val Dist 5.3682%	 Val Loss 0.2833
Saved epoch model
Saved best model

Epoch: 26/60

	Train Loss 0.2718	 Learning Rate 0.0020000
	Val Dist 5.6923%	 Val Loss 0.2940
Saved epoch model

Epoch: 27/60

	Train Loss 0.2707	 Learning Rate 0.0020000
	Val Dist 5.3304%	 Val Loss 0.2730
Saved epoch model
Saved best model

Epoch: 28/60

	Train Loss 0.2626	 Learning Rate 0.0020000
	Val Dist 5.2375%	 Val Loss 0.2695
Saved epoch model
Saved best model

Epoch: 29/60

	Train Loss 0.2598	 Learning Rate 0.0020000
	Val Dist 5.2477%	 Val Loss 0.2689
Saved epoch model

Epoch: 30/60

	Train Loss 0.2563	 Learning Rate 0.0020000
	Val Dist 5.2113%	 Val Loss 0.2671
Saved epoch model
Saved best model

Epoch: 31/60

	Train Loss 0.2478	 Learning Rate 0.0020000
	Val Dist 5.1012%	 Val Loss 0.2652
Saved epoch model
Saved best model

Epoch: 32/60

	Train Loss 0.2433	 Learning Rate 0.0020000
	Val Dist 5.1534%	 Val Loss 0.2741
Saved epoch model

Epoch: 33/60

	Train Loss 0.2432	 Learning Rate 0.0020000
	Val Dist 5.0390%	 Val Loss 0.2706
Saved epoch model
Saved best model

Epoch: 34/60

	Train Loss 0.2327	 Learning Rate 0.0020000
	Val Dist 5.0325%	 Val Loss 0.2686
Saved epoch model
Saved best model

Epoch: 35/60

Epoch 00035: reducing learning rate of group 0 to 1.0000e-03.
	Train Loss 0.2323	 Learning Rate 0.0020000
	Val Dist 5.0551%	 Val Loss 0.2644
Saved epoch model

Epoch: 36/60

	Train Loss 0.1974	 Learning Rate 0.0010000
	Val Dist 4.5493%	 Val Loss 0.2477
Saved epoch model
Saved best model

Epoch: 37/60

	Train Loss 0.1833	 Learning Rate 0.0010000
	Val Dist 4.5364%	 Val Loss 0.2517
Saved epoch model
Saved best model

Epoch: 38/60

	Train Loss 0.1781	 Learning Rate 0.0010000
	Val Dist 4.5192%	 Val Loss 0.2499
Saved epoch model
Saved best model

Epoch: 39/60

	Train Loss 0.1732	 Learning Rate 0.0010000
	Val Dist 4.4137%	 Val Loss 0.2452
Saved epoch model
Saved best model

Epoch: 40/60

	Train Loss 0.1721	 Learning Rate 0.0010000
	Val Dist 4.4544%	 Val Loss 0.2470
Saved epoch model

Epoch: 41/60

	Train Loss 0.1697	 Learning Rate 0.0010000
	Val Dist 4.4082%	 Val Loss 0.2480
Saved epoch model
Saved best model

Epoch: 42/60

	Train Loss 0.1635	 Learning Rate 0.0010000
	Val Dist 4.3589%	 Val Loss 0.2444
Saved epoch model
Saved best model

Epoch: 43/60

Epoch 00043: reducing learning rate of group 0 to 5.0000e-04.
	Train Loss 0.1635	 Learning Rate 0.0010000
	Val Dist 4.3504%	 Val Loss 0.2438
Saved epoch model
Saved best model

Epoch: 44/60

	Train Loss 0.1477	 Learning Rate 0.0005000
	Val Dist 4.2538%	 Val Loss 0.2463
Saved epoch model
Saved best model

Epoch: 45/60

	Train Loss 0.1401	 Learning Rate 0.0005000
	Val Dist 4.2129%	 Val Loss 0.2452
Saved epoch model
Saved best model

Epoch: 46/60

	Train Loss 0.1387	 Learning Rate 0.0005000
	Val Dist 4.1368%	 Val Loss 0.2432
Saved epoch model
Saved best model

Epoch: 47/60

	Train Loss 0.1349	 Learning Rate 0.0005000
	Val Dist 4.1578%	 Val Loss 0.2459
Saved epoch model

Epoch: 48/60

	Train Loss 0.1329	 Learning Rate 0.0005000
	Val Dist 4.1357%	 Val Loss 0.2444
Saved epoch model
Saved best model

Epoch: 49/60

	Train Loss 0.1316	 Learning Rate 0.0005000
	Val Dist 4.1238%	 Val Loss 0.2404
Saved epoch model
Saved best model

Epoch: 50/60

Epoch 00050: reducing learning rate of group 0 to 2.5000e-04.
	Train Loss 0.1300	 Learning Rate 0.0005000
	Val Dist 4.1251%	 Val Loss 0.2472
Saved epoch model

Epoch: 51/60

	Train Loss 0.1242	 Learning Rate 0.0002500
	Val Dist 4.0586%	 Val Loss 0.2472
Saved epoch model
Saved best model

Epoch: 52/60

	Train Loss 0.1197	 Learning Rate 0.0002500
	Val Dist 4.0696%	 Val Loss 0.2471
Saved epoch model

Epoch: 53/60

	Train Loss 0.1184	 Learning Rate 0.0002500
	Val Dist 4.0706%	 Val Loss 0.2468
Saved epoch model

Epoch: 54/60

	Train Loss 0.1176	 Learning Rate 0.0002500
	Val Dist 4.0078%	 Val Loss 0.2462
Saved epoch model
Saved best model

Epoch: 55/60

	Train Loss 0.1156	 Learning Rate 0.0002500
	Val Dist 4.0298%	 Val Loss 0.2450
Saved epoch model

Epoch: 56/60

	Train Loss 0.1151	 Learning Rate 0.0002500
	Val Dist 4.0269%	 Val Loss 0.2460
Saved epoch model

Epoch: 57/60

	Train Loss 0.1144	 Learning Rate 0.0002500
	Val Dist 4.0351%	 Val Loss 0.2456
Saved epoch model

Epoch: 58/60

Epoch 00058: reducing learning rate of group 0 to 1.2500e-04.
	Train Loss 0.1128	 Learning Rate 0.0002500
	Val Dist 4.0192%	 Val Loss 0.2501
Saved epoch model

Epoch: 59/60

	Train Loss 0.1098	 Learning Rate 0.0001250
	Val Dist 3.9887%	 Val Loss 0.2451
Saved epoch model
Saved best model

Epoch: 60/60

	Train Loss 0.1079	 Learning Rate 0.0001250
	Val Dist 3.9582%	 Val Loss 0.2473
Saved epoch model
Saved best model

VBox(children=(Label(value='160.125 MB of 310.825 MB uploaded\r'), FloatProgress(value=0.5151614380071907, max…

# Retrain

In [ ]:
root = '/content/11-785-f24-hw3p2/'

# Feel free to add more items here
config = {
    "beam_width" : 3,
    "lr"         : 2e-3,
    "epochs"     : 50,
    "batch_size" : 64  # Increase if your device can handle it
}

# You may pass this as a parameter to the dataset class above
# This will help modularize your implementation
transforms = [] # set of tranformations

In [ ]:
#TODO


# Define CTC loss as the criterion. How would the losses be reduced?
# CTC Loss: https://pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html
# Refer to the handout for hints
criterion = torch.nn.CTCLoss(blank=0, zero_infinity=True)

optimizer =  torch.optim.AdamW(model.parameters(), lr=config['lr'])

# Declare the decoder. Use the CTC Beam Decoder to decode phonemes
# CTC Beam Decoder Doc: https://github.com/parlance/ctcdecode
decoder = CTCBeamDecoder(labels=LABELS, model_path=None, beam_width=config['beam_width'], log_probs_input=True)

# scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=config['epochs'], eta_min=0)
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, threshold=0.02, verbose=True)

# Mixed Precision, if you need it
scaler = torch.cuda.amp.GradScaler()

In [ ]:
model, optimizer, scheduler, epoch, metric = load_model("/content/hw3p2/final/last.pth", model,'valid_dist',optimizer,scheduler)

In [ ]:
scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.5, patience=3, threshold=0.02, verbose=True)

In [ ]:
run = wandb.init(
    name = "final-submission-contTrain", ## Wandb creates random run names if you skip this field
    reinit = True, ### Allows reinitalizing runs when you re-run this cell
    # run_id = ### Insert specific run id here if you want to resume a previous run
    # resume = "must" ### You need this to resume previous runs, but comment out reinit = True when using this
    project = "hw3p2-ablations", ### Project should be created in your wandb account
    config = config ### Wandb Config for your run
)

In [ ]:
last_epoch_completed = 0
start = last_epoch_completed
end = config["epochs"]
best_lev_dist = float("inf") # if you're restarting from some checkpoint, use what you saw there.
epoch_model_path = '/content/hw3p2/final/contTrain/last.pth'#TODO set the model path( Optional, you can just store best one. Make sure to make the changes below )
best_model_path = '/content/hw3p2/final/contTrain/best.pth'#TODO set best model path

In [ ]:
torch.cuda.empty_cache()
gc.collect()

#TODO: Please complete the training loop

for epoch in range(0, config['epochs']):

    print("\nEpoch: {}/{}".format(epoch+1, config['epochs']))

    curr_lr = optimizer.param_groups[0]['lr'] #TODO

    train_loss              = train_model(model, train_loader, criterion, optimizer) #TODO
    valid_loss, valid_dist  = validate_model(model, val_loader, decoder, phoneme_map=LABELS) #TODO
    scheduler.step(valid_dist)

    print("\tTrain Loss {:.04f}\t Learning Rate {:.07f}".format(train_loss, curr_lr))
    print("\tVal Dist {:.04f}%\t Val Loss {:.04f}".format(valid_dist, valid_loss))


    wandb.log({
        'train_loss': train_loss,
        'valid_dist': valid_dist,
        'valid_loss': valid_loss,
        'lr'        : curr_lr
    })

    save_model(model, optimizer, scheduler, ['valid_dist', valid_dist], epoch, epoch_model_path)
    wandb.save(epoch_model_path)
    print("Saved epoch model")

    if valid_dist <= best_lev_dist:
        best_lev_dist = valid_dist
        save_model(model, optimizer, scheduler, ['valid_dist', valid_dist], epoch, best_model_path)
        wandb.save(best_model_path)
        print("Saved best model")
      # You may find it interesting to exlplore Wandb Artifcats to version your models
run.finish()

Epoch: 1/50

	Train Loss 0.2502	 Learning Rate 0.0010000
	Val Dist 6.0536%	 Val Loss 0.2954
Saved epoch model
Saved best model

Epoch: 2/50

	Train Loss 0.2570	 Learning Rate 0.0010000
	Val Dist 5.9214%	 Val Loss 0.2851
Saved epoch model
Saved best model

Epoch: 3/50

	Train Loss 0.2586	 Learning Rate 0.0010000
	Val Dist 5.9716%	 Val Loss 0.2906
Saved epoch model

Epoch: 4/50

	Train Loss 0.2575	 Learning Rate 0.0010000
	Val Dist 5.9020%	 Val Loss 0.2913
Saved epoch model
Saved best model

Epoch: 5/50

	Train Loss 0.2472	 Learning Rate 0.0010000
	Val Dist 5.9104%	 Val Loss 0.2905
Saved epoch model

Epoch: 6/50

	Train Loss 0.2503	 Learning Rate 0.0010000
	Val Dist 5.7314%	 Val Loss 0.2841
Saved epoch model
Saved best model

Epoch: 7/50

	Train Loss 0.2533	 Learning Rate 0.0010000
	Val Dist 5.9142%	 Val Loss 0.2901
Saved epoch model

Epoch: 8/50

	Train Loss 0.2465	 Learning Rate 0.0010000
	Val Dist 5.7575%	 Val Loss 0.2840
Saved epoch model

Epoch: 9/50

	Train Loss 0.2412	 Learning Rate 0.0010000
	Val Dist 5.6823%	 Val Loss 0.2833
Saved epoch model
Saved best model

Epoch: 10/50

Epoch 00010: reducing learning rate of group 0 to 5.0000e-04.
	Train Loss 0.2364	 Learning Rate 0.0010000
	Val Dist 5.7523%	 Val Loss 0.2814
Saved epoch model

Epoch: 11/50

	Train Loss 0.2169	 Learning Rate 0.0005000
	Val Dist 5.4489%	 Val Loss 0.2706
Saved epoch model
Saved best model

Epoch: 12/50

	Train Loss 0.2111	 Learning Rate 0.0005000
	Val Dist 5.4252%	 Val Loss 0.2708
Saved epoch model
Saved best model

Epoch: 13/50

	Train Loss 0.2054	 Learning Rate 0.0005000
	Val Dist 5.3946%	 Val Loss 0.2663
Saved epoch model
Saved best model

Epoch: 14/50

	Train Loss 0.2026	 Learning Rate 0.0005000
	Val Dist 5.3052%	 Val Loss 0.2674
Saved epoch model
Saved best model

Epoch: 15/50

	Train Loss 0.2011	 Learning Rate 0.0005000
	Val Dist 5.2943%	 Val Loss 0.2687
Saved epoch model
Saved best model

Epoch: 16/50

	Train Loss 0.2008	 Learning Rate 0.0005000
	Val Dist 5.4179%	 Val Loss 0.2732
Saved epoch model

Epoch: 17/50

	Train Loss 0.2003	 Learning Rate 0.0005000
	Val Dist 5.3262%	 Val Loss 0.2701
Saved epoch model

Epoch: 18/50

Epoch 00018: reducing learning rate of group 0 to 2.5000e-04.
	Train Loss 0.1974	 Learning Rate 0.0005000
	Val Dist 5.3305%	 Val Loss 0.2693
Saved epoch model

Epoch: 19/50

	Train Loss 0.1864	 Learning Rate 0.0002500
	Val Dist 5.1954%	 Val Loss 0.2654
Saved epoch model
Saved best model

Epoch: 20/50

	Train Loss 0.1828	 Learning Rate 0.0002500
	Val Dist 5.1702%	 Val Loss 0.2627
Saved epoch model
Saved best model

Epoch: 21/50

	Train Loss 0.1819	 Learning Rate 0.0002500
	Val Dist 5.1195%	 Val Loss 0.2629
Saved epoch model
Saved best model

Epoch: 22/50

	Train Loss 0.1810	 Learning Rate 0.0002500
	Val Dist 5.1420%	 Val Loss 0.2640
Saved epoch model

Epoch: 23/50

Epoch 00023: reducing learning rate of group 0 to 1.2500e-04.
	Train Loss 0.1784	 Learning Rate 0.0002500
	Val Dist 5.1378%	 Val Loss 0.2659
Saved epoch model

Epoch: 24/50

	Train Loss 0.1730	 Learning Rate 0.0001250
	Val Dist 5.0419%	 Val Loss 0.2621
Saved epoch model
Saved best model

Epoch: 25/50

	Train Loss 0.1713	 Learning Rate 0.0001250
	Val Dist 5.0451%	 Val Loss 0.2617
Saved epoch model

Epoch: 26/50

	Train Loss 0.1715	 Learning Rate 0.0001250
	Val Dist 5.0583%	 Val Loss 0.2607
Saved epoch model

Epoch: 27/50

	Train Loss 0.1698	 Learning Rate 0.0001250
	Val Dist 5.0616%	 Val Loss 0.2596
Saved epoch model

Epoch: 28/50

Epoch 00028: reducing learning rate of group 0 to 6.2500e-05.
	Train Loss 0.1684	 Learning Rate 0.0001250
	Val Dist 5.0817%	 Val Loss 0.2616
Saved epoch model

Epoch: 29/50

	Train Loss 0.1674	 Learning Rate 0.0000625
	Val Dist 5.0357%	 Val Loss 0.2607
Saved epoch model
Saved best model

Epoch: 30/50

	Train Loss 0.1659	 Learning Rate 0.0000625
	Val Dist 5.0567%	 Val Loss 0.2625
Saved epoch model

Epoch: 31/50

	Train Loss 0.1657	 Learning Rate 0.0000625
	Val Dist 5.0135%	 Val Loss 0.2612
Saved epoch model
Saved best model

Epoch: 32/50

Epoch 00032: reducing learning rate of group 0 to 3.1250e-05.
	Train Loss 0.1640	 Learning Rate 0.0000625
	Val Dist 5.0251%	 Val Loss 0.2617
Saved epoch model

Epoch: 33/50

	Train Loss 0.1659	 Learning Rate 0.0000313
	Val Dist 5.0105%	 Val Loss 0.2616
Saved epoch model
Saved best model

Epoch: 34/50

	Train Loss 0.1643	 Learning Rate 0.0000313
	Val Dist 5.0064%	 Val Loss 0.2617
Saved epoch model
Saved best model

Epoch: 35/50

	Train Loss 0.1632	 Learning Rate 0.0000313
	Val Dist 4.9866%	 Val Loss 0.2613
Saved epoch model
Saved best model

Epoch: 36/50

Epoch 00036: reducing learning rate of group 0 to 1.5625e-05.
	Train Loss 0.1643	 Learning Rate 0.0000313
	Val Dist 4.9967%	 Val Loss 0.2616
Saved epoch model

Epoch: 37/50

	Train Loss 0.1627	 Learning Rate 0.0000156
	Val Dist 4.9854%	 Val Loss 0.2611
Saved epoch model
Saved best model

Epoch: 38/50

	Train Loss 0.1628	 Learning Rate 0.0000156
	Val Dist 4.9887%	 Val Loss 0.2613
Saved epoch model

Epoch: 39/50

	Train Loss 0.1619	 Learning Rate 0.0000156
	Val Dist 4.9814%	 Val Loss 0.2613
Saved epoch model
Saved best model

Epoch: 40/50

Epoch 00040: reducing learning rate of group 0 to 7.8125e-06.
	Train Loss 0.1620	 Learning Rate 0.0000156
	Val Dist 4.9863%	 Val Loss 0.2608
Saved epoch model

Epoch: 41/50

	Train Loss 0.1620	 Learning Rate 0.0000078
	Val Dist 4.9875%	 Val Loss 0.2609
Saved epoch model

Epoch: 42/50

	Train Loss 0.1609	 Learning Rate 0.0000078
	Val Dist 4.9834%	 Val Loss 0.2609
Saved epoch model

Epoch: 43/50

	Train Loss 0.1622	 Learning Rate 0.0000078
	Val Dist 4.9741%	 Val Loss 0.2604
Saved epoch model
Saved best model

Epoch: 44/50

Epoch 00044: reducing learning rate of group 0 to 3.9063e-06.
	Train Loss 0.1619	 Learning Rate 0.0000078
	Val Dist 4.9893%	 Val Loss 0.2619
Saved epoch model

Epoch: 45/50

	Train Loss 0.1614	 Learning Rate 0.0000039
	Val Dist 4.9691%	 Val Loss 0.2606
Saved epoch model
Saved best model

Epoch: 46/50

	Train Loss 0.1611	 Learning Rate 0.0000039
	Val Dist 4.9764%	 Val Loss 0.2612
Saved epoch model

Epoch: 47/50

	Train Loss 0.1612	 Learning Rate 0.0000039
	Val Dist 4.9707%	 Val Loss 0.2606
Saved epoch model

Epoch: 48/50

Epoch 00048: reducing learning rate of group 0 to 1.9531e-06.
	Train Loss 0.1612	 Learning Rate 0.0000039
	Val Dist 4.9675%	 Val Loss 0.2608
Saved epoch model
Saved best model

Epoch: 49/50

	Train Loss 0.1603	 Learning Rate 0.0000020
	Val Dist 4.9724%	 Val Loss 0.2608
Saved epoch model

Epoch: 50/50

	Train Loss 0.1606	 Learning Rate 0.0000020
	Val Dist 4.9773%	 Val Loss 0.2612
Saved epoch model

VBox(children=(Label(value='103.211 MB of 104.811 MB uploaded\r'), FloatProgress(value=0.9847377297722325, max…

# Generate Predictions and Submit to Kaggle

In [ ]:
model2, _, _, _, _ = load_model("/content/hw3p2/final/contTrain/best.pth", model,'valid_dist')

In [ ]:
#TODO: Make predictions

# Follow the steps below:
# 1. Create a new object for CTCBeamDecoder with larger (why?) number of beams
# 2. Get prediction string by decoding the results of the beam decoder

TEST_BEAM_WIDTH = 10

test_decoder    = CTCBeamDecoder(labels=LABELS, model_path=None, beam_width=TEST_BEAM_WIDTH, log_probs_input=True)
results = []

model.eval()
print("Testing")
for data in tqdm(test_loader):

    x, lx   = data
    # print(x.shape)
    # print(lx.shape)
    x       = x.to(device)

    with torch.no_grad():
        h, lh = model(x, lx)
        h = torch.permute(h, (1, 0, 2))

    prediction_string= decode_prediction(h, lh, test_decoder, LABELS)

    results.extend(prediction_string)
    #TODO save the output in results array.

    del x, lx, h, lh
    torch.cuda.empty_cache()

Testing

100%|██████████| 41/41 [00:26<00:00,  1.56it/s]

In [ ]:
data_dir = f"random_submission.csv"
df = pd.read_csv(data_dir)
df.label = results
df.to_csv('submission5.csv', index = False)

In [ ]:
!kaggle competitions submit -c hw3p2-785-f24 -f submission.csv -m "I made it!"